/* Banco N4: palabras [escritura, lectura, inglés, español, otras lecturas válidas, 1 = ambigua]
   y kanjis [carácter, inglés, español, on, kun]. Formato y uso en bank/bank.js. */
BANK.add("N4", {
  words: [
    ["お土産","おみやげ",["souvenir"],["regalo","souvenir"]],
    ["お嬢さん","おじょうさん",["(someone's) daughter (polite)"],["hija"]],
    ["お子さん","おこさん",["(someone else's) child (polite)"],["niño"]],
    ["お宅","おたく",["(someone else's) house","home -- polite word for 家 (いえ) --"],["su casa (o vuestra casa)","su hogar"]],
    ["お礼","おれい",["expression of gratitude","thanking"],["agradecimiento","expresión de gratitud"]],
    ["お祝い","おいわい",["congratulation","celebration"],["celebración"]],
    ["お祭り","おまつり",["festival"],["festival","festín"]],
    ["お見舞い","おみまい",["calling on someone who is ill","visit"],["preguntar por la salud de alguien"]],
    ["お金持ち","おかねもち",["rich person","wealthy person"],["persona rica"]],
    ["お陰","おかげ",["thanks or owing to"],["gracias a (algo o alguien)"]],
    ["この間","このあいだ",["the other day","recently"],["el otro día","recientemente"]],
    ["この頃","このごろ",["these days","nowadays"],["recientemente","últimamente"]],
    ["ご主人","ごしゅじん",["(your, her) husband"],["(su) marido","(su) esposo"]],
    ["ご存じ","ごぞんじ",["knowing","acquaintance"],["lo sabe","lo conoce (usted)"]],
    ["一度","いちど",["once","one time"],["una vez","un tiempo"]],
    ["一杯","いっぱい",["full","to the utmost"],["copa de ..","bebida"]],
    ["一生懸命","いっしょうけんめい",["very hard (as in \"to work hard\")","with utmost effort"],["muy difícil","con todo el esfuerzo posible"]],
    ["丁寧","ていねい",["polite","courteous"],["cortés","educado"]],
    ["上がる","あがる",["to rise","to go up"],["entrar","subir"]],
    ["下げる","さげる",["to lower (v.t.)","to hang"],["colgar(algo)","bajar(algo)"]],
    ["下りる","おりる",["to get down","to go"],["bajarse de un vehículo","salir"]],
    ["下る","さがる",["to descend","to drop"],["colgarse","disminuir"],["くだる"]],
    ["下宿","げしゅく",["lodging","boarding house"],["alojamiento","hospedaje"]],
    ["下着","したぎ",["underwear"],["ropa interior"]],
    ["不便","ふべん",["inconvenience"],["inconveniente","incomodidad"]],
    ["世界","せかい",["world"],["mundo","sociedad"]],
    ["世話","せわ",["care","looking after"],["cuidado (de alguien)","ayuda"]],
    ["両方","りょうほう",["both sides","both parties"],["ambos lados","ambos grupos"]],
    ["中々","なかなか",["very","considerably"],["muy","considerablemente"]],
    ["中学校","ちゅうがっこう",["junior high school pupil"],["escuela secundaria"]],
    ["久しぶり","ひさしぶり",["it has been a long time","for the first time in a long time"],["mucho tiempo (desde la última vez)","ha pasado mucho tiempo (desde la última vez que te vi, escribí, etc.,)"]],
    ["乗り換える","のりかえる",["to transfer (trains)","to change (bus, train, etc.)"],["hacer transferencia (de trenes)","transbordar (autobús, tren)"]],
    ["乗り物","のりもの",["vehicle"],["vehículo"]],
    ["乾く","かわく",["to get dry"],["secarse"]],
    ["予定","よてい",["plans","arrangement"],["planes","preparativo"]],
    ["予約","よやく",["reservation"],["reservar","hacer una reserva"]],
    ["予習","よしゅう",["preparation of lessons (for class)"],["preparar la lección con antelación","estudio de preparación"]],
    ["事","こと",["thing(s)","matter(s)"],["cosa","hecho"]],
    ["事務所","じむしょ",["office"],["oficina"]],
    ["事故","じこ",["accident"],["accidente","incidente"]],
    ["亡くなる","なくなる",["to pass away"],["morir"]],
    ["交通","こうつう",["traffic","transportation"],["comunicación","transportación"]],
    ["人口","じんこう",["population"],["población","número de habitantes"]],
    ["人形","にんぎょう",["doll","figure"],["muñeco","títere"]],
    ["今夜","こんや",["this evening","tonight"],["esta noche"]],
    ["今度","こんど",["now","this time"],["ahora","esta vez"]],
    ["仕方","しかた",["way (of doing something)"],["manera","modo"]],
    ["代わり","かわり",["substitute","replacement"],["cambio","lugar"]],
    ["以上","いじょう",["more than","this is all"],["nada menos que","por lo menos"]],
    ["以下","いか",["less than","below"],["no exceder","y hacia abajo"]],
    ["以内","いない",["within","less (no more) than"],["dentro (plazo","espacio)"]],
    ["以外","いがい",["other than","with the exception of"],["excepto","con la excepción"]],
    ["会場","かいじょう",["venue","meeting place"],["asamblea","lugar de reunión"]],
    ["会話","かいわ",["conversation"],["conversación","plática"]],
    ["会議","かいぎ",["business meeting","conference"],["congreso","encuentro"]],
    ["会議室","かいぎしつ",["conference room"],["sala de reuniones"]],
    ["伝える","つたえる",["to convey (a message)","to tell"],["transportar","reportar"]],
    ["伺う","うかがう",["humble form of 行く (いく)","聞く (きく) and 来る (くる)"],["visitar","pedir"]],
    ["似る","にる",["to resemble","to be similar"],["parecerse","ser semejante"]],
    ["住所","じゅうしょ",["address","place of residence"],["dirección (casa)","residencia"]],
    ["例えば","たとえば",["for example","e.g."],["por ejemplo","ej."]],
    ["倍","ばい",["double"],["doble","veces"]],
    ["倒れる","たおれる",["to collapse","to break down"],["colapsar","averiarse"]],
    ["値段","ねだん",["price"],["precio","coste"]],
    ["僕","ぼく",["I (used by men towards those of equal or lower status)"],["yo (varón)"]],
    ["億","おく",["hundred million"],["cien millones","10 elevado a 8"]],
    ["優しい","やさしい",["kind (person)","gentle (person)"],["tierno","bueno"]],
    ["先輩","せんぱい",["senior members of a group"],["sufijo que indica mayor antigüedad que uno en el trabajo escuela etc"]],
    ["光","ひかり",["light"],["rayo","luz"]],
    ["光る","ひかる",["to shine","to glitter"],["brillar"]],
    ["入学","にゅうがく",["admission (to a school or university)","entrance"],["ingresar en una escuela","ingresar en un centro de estudios"]],
    ["入院","にゅういん",["hospitalization","hospitalisation"],["hospitalización","ingresar en un hospital"]],
    ["全然","ぜんぜん",["not at all","wholly"],["completamente"]],
    ["公務員","こうむいん",["government worker","public servant"],["funcionario público","empleado del gobierno"]],
    ["具合","ぐあい",["condition","state"],["condición","salud"]],
    ["内","うち",["within","inside"],["dentro"],["ない"]],
    ["再来月","さらいげつ",["the month after next"],["dentro de dos meses","el mes que sigue al que viene"]],
    ["再来週","さらいしゅう",["the week after next"],["dentro de dos semanas","la semana que sigue a la que viene"]],
    ["写す","うつす",["to copy (v.t.)","to photograph"],["transcribir","duplicar"]],
    ["冷える","ひえる",["to grow cold","to cool down"],["enfriarse","congelarse"]],
    ["冷房","れいぼう",["cooling","air conditioning"],["enfriamiento"]],
    ["凄い","すごい",["terrific","great"],["terrible","espantoso"]],
    ["出席","しゅっせき",["attendance","presence"],["asistencia","presencia"]],
    ["出発","しゅっぱつ",["departure","leaving"],["partida (de irse)"]],
    ["別","べつ",["distinction","different"],["separar","aparte"]],
    ["別れる","わかれる",["to part from","to separate"],["dividirse","separar"]],
    ["利用","りよう",["use","utilization"],["uso","utilización"]],
    ["割れる","われる",["to break"],["romperse","fracturarse"]],
    ["割合","わりあい",["rate","ratio"],["porcentaje","proporción"]],
    ["力","ちから",["strength","power"],["fuerza","energía"],["りょく"]],
    ["動く","うごく",["to move"],["moverse","cambiarse"]],
    ["動物園","どうぶつえん",["zoo"],["zoo","zoológico"]],
    ["勝つ","かつ",["to win"],["ganar","ganar"]],
    ["匂い","におい",["odor","smell"],["olor"]],
    ["包む","つつむ",["to wrap","to cover"],["estar sumergido en","estar envuelto por"]],
    ["医学","いがく",["medical science"],["medicina","ciencia médica"]],
    ["十分","じゅうぶん",["enough"],["suficiente","bastante"]],
    ["卒業","そつぎょう",["graduation"],["graduación"]],
    ["危険","きけん",["danger","risk"],["peligro","riesgo"]],
    ["原因","げんいん",["cause","origin"],["causa","fuente"]],
    ["厳しい","きびしい",["hard","rigorous"],["severo","estricto"]],
    ["参る","まいる",["humble expression for 行く and 来る"],["ir","venir"]],
    ["反対","はんたい",["oppose","opposition"],["opuesto","contrario"]],
    ["取り替える","とりかえる",["to exchange","to replace"],["intercambiar","reemplazar"]],
    ["受ける","うける",["to take (an examination, interview, etc.)","to receive"],["emprender","aceptar"]],
    ["受付","うけつけ",["reception(ist) desk"],["recepción","información"]],
    ["召し上がる","めしあがる",["-- honorific form of 食べる (たべる) and 飲む (のむ) --"],["comer"]],
    ["台風","たいふう",["typhoon"],["tifón"]],
    ["叱る","しかる",["to scold"],["regañar","echar la bronca"]],
    ["合う","あう",["to fit","to match"],["colocar","satisfacer"]],
    ["向かう","むかう",["to face","to go towards"],["encarar","ir hacia"]],
    ["君","きみ",["you (informal for men)"],["(fam) tú","ti"],[],1],
    ["君","くん",["Mr","master"],["sufijo para muchachos","de los mayores a los muchachos o entre muchachos"],[],1],
    ["周り","まわり",["surroundings"],["los alrededores","el perímetro"]],
    ["味","あじ",["flavor","taste"],["sabor","gusto"]],
    ["味噌","みそ",["miso","bean paste"],["miso (sopa japonesa)"]],
    ["品物","しなもの",["goods"],["artículo"]],
    ["喉","のど",["throat"],["garganta"]],
    ["喜ぶ","よろこぶ",["to rejoice","to be delighted"],["deleitarse","alegrarse"]],
    ["嘘","うそ",["lie"],["mentira","falsedad"]],
    ["噛む","かむ",["to bite","to chew"],["mascar","morder"]],
    ["国際","こくさい",["international"],["internacional"]],
    ["地理","ちり",["geography"],["geografía"]],
    ["地震","じしん",["earthquake"],["terremoto"]],
    ["坂","さか",["slope","hill"],["cuesta","pendiente"]],
    ["堅","かたい",["solid","hard"],["duro","sólido"]],
    ["場合","ばあい",["case","situation"],["caso","situación"]],
    ["場所","ばしょ",["place","location"],["lugar","ubicación"]],
    ["塗る","ぬる",["to paint","to plaster"],["pintar","barnizar"]],
    ["増える","ふえる",["to increase","to multiply"],["aumentar","multiplicar"]],
    ["壁","かべ",["wall"],["muro","pared"]],
    ["壊す","こわす",["to break","to break down"],["romper","romper"]],
    ["壊れる","こわれる",["to be broken","to break"],["romperse","romper"]],
    ["売り場","うりば",["place where things are sold"],["mostrador (de tienda)"]],
    ["変","へん",["strange","odd"],["inusual","extraño"]],
    ["変える","かえる",["to change","to alter"],["cambiar","variar"]],
    ["変わる","かわる",["to change (v.i.)","to be transformed"],["cambiar","transformarse"]],
    ["夢","ゆめ",["a dream"],["sueño","visión"]],
    ["大事","だいじ",["important","valuable"],["importante","valioso"]],
    ["大体","だいたい",["approximately","in most cases"],["más o menos","casi"]],
    ["大分","だいぶ",["fairly well","to a large extent"],["considerablemente","mucho"],["だいぶん"]],
    ["大学生","だいがくせい",["college student","university student"],["estudiante universitario","colegial"]],
    ["大抵","たいてい",["generally","usually"],["generalmente","en general"]],
    ["天気予報","てんきよほう",["weather forecast"],["reporte meteorológico"]],
    ["太る","ふとる",["to gain weight"],["engordar","hacerse gordo"]],
    ["夫","おっと",["husband"],["marido","hombre"]],
    ["失敗","しっぱい",["failure","mistake"],["fallo","fracaso"]],
    ["失礼","しつれい",["discourtesy","impoliteness"],["descortesía","mala educación"]],
    ["女性","じょせい",["woman"],["sexo femenino","mujer (mejor término que onna)"]],
    ["妻","つま",["wife (humble)"],["esposa","mujer"]],
    ["始める","はじめる",["to start","to begin"],["empezar","comenzar"]],
    ["娘","むすめ",["daughter (humble)"],["hija","chica"]],
    ["嬉しい","うれしい",["to be happy","to be glad"],["feliz","alegre"]],
    ["子","こ",["child"],["hijo","hija"],[],1],
    ["子","ね",["the Rat (first sign of the Chinese zodiac)"],["rata (signo del zodiaco chino)"],[],1],
    ["字","じ",["letter","character"],["letra (carácter tipográfico)"],[],1],
    ["字","あざ",["section of village"],["sección de una villa"],[],1],
    ["季節","きせつ",["season (in reference to weather)"],["temporada"]],
    ["安全","あんぜん",["safety","security"],["seguro"]],
    ["安心","あんしん",["peace of mind","relief"],["alivio","paz mental"]],
    ["客","きゃく",["guest","customer"],["huésped","visitante"]],
    ["家内","かない",["(one's own) wife"],["esposa"]],
    ["寂しい","さびしい",["lonely","lonesome"],["solo","solitario"]],
    ["寄る","よる",["to stop by"],["visitar"]],
    ["寝坊","ねぼう",["sleeping in late"],["dormir hasta tarde"]],
    ["寺","てら",["Buddhist temple"],["templo budista","templo"]],
    ["専門","せんもん",["major","speciality"],["especialidad"]],
    ["将来","しょうらい",["(in the) future","prospects"],["en el futuro"]],
    ["尋ねる","たずねる",["to inquire (same as 質問する)"],["preguntar","averiguar"]],
    ["小学校","しょうがっこう",["elementary school"],["escuela primaria"]],
    ["小説","しょうせつ",["novel"],["novela"]],
    ["小鳥","ことり",["small bird"],["pajarito"]],
    ["届ける","とどける",["to deliver (v.t.)"],["enviar","llevar y entregar"]],
    ["屋上","おくじょう",["rooftop"],["azotea"]],
    ["展覧会","てんらんかい",["exhibition"],["exhibición","exposición"]],
    ["島","しま",["island"],["isla"]],
    ["工場","こうじょう",["factory"],["fábrica"],["こうば"]],
    ["工業","こうぎょう",["(manufacturing) industry"],["industria (manufacturera)"]],
    ["差し上げる","さしあげる",["-- humble expression for あげる --"],["dar","ofrecer"]],
    ["市","し",["city"],["ciudad"],[],1],
    ["市","いち",["market","fair"],["mercado","feria"],[],1],
    ["市民","しみん",["citizen"],["ciudadano"]],
    ["布団","ふとん",["futon"],["\"futon\": colchón japonés","edredón japonés"]],
    ["席","せき",["a seat"],["asiento","plaza"]],
    ["帰り","かえり",["return","coming back"],["regreso","vuelta"]],
    ["床屋","とこや",["barber's (shop)"],["barbero","barbería"]],
    ["店員","てんいん",["clerk","shop-employee"],["dependiente","vendedor de una tienda"]],
    ["建て","~だて",["~ storied","separate housing"],["de ~ plantas"]],
    ["建てる","たてる",["to build"],["construir","edificar"]],
    ["引き出し","ひきだし",["drawer"],["cajón","gaveta"]],
    ["引っ越す","ひっこす",["to move to a new place of residence"],["mudarse","cambiar de residencia"]],
    ["形","かたち",["shape"],["forma","figura"]],
    ["役に立つ","やくにたつ",["to be helpful","to be useful"],["servir de ayuda","ser útil"]],
    ["彼","かれ",["he","boyfriend"],["eso","aquello"]],
    ["彼ら","かれら",["they (usually male)"],["ellos"]],
    ["彼女","かのじょ",["girlfriend","she"],["ella"]],
    ["復習","ふくしゅう",["review (of lessons)","revision"],["repaso (en el estudio)"]],
    ["心","こころ",["heart","mind"],["mente","corazón"],["しん"]],
    ["心配","しんぱい",["worry","concern"],["preocupación","preocupar"]],
    ["必ず","かならず",["surely","certainly"],["sin falta","necesariamente"]],
    ["必要","ひつよう",["necessary"],["necesario","esencial"]],
    ["忘れ物","わすれもの",["lost article","something forgotten"],["objeto perdido","algo olvidado"]],
    ["怒る","おこる",["to get angry","to scold angrily"],["enojarse","enfadarse"]],
    ["怖い","こわい",["scary","frightening"],["asustadizo","temeroso"]],
    ["思い出す","おもいだす",["to recall","to remember"],["recordar"]],
    ["思う","おもう",["to think","to feel"],["pensar","sentir"]],
    ["急","きゅう",["urgent","sudden"],["prisa","urgencia"]],
    ["急ぐ","いそぐ",["to hurry","to be in a hurry"],["apresurar","apurar"]],
    ["急行","きゅうこう",["express train or bus"],["ir rápidamente","personarse enseguida"]],
    ["恥ずかしい","はずかしい",["ashamed","embarrassed"],["tímido","avergonzado"]],
    ["息子","むすこ",["(humble) son"],["hijo (varón)"]],
    ["悲しい","かなしい",["sad","sorrowful"],["triste","tristeza"]],
    ["意見","いけん",["opinion","view"],["aconsejar","advertir"]],
    ["慣れる","なれる",["to grow accustomed to"],["acostumbrarse"]],
    ["戦争","せんそう",["war"],["hacer la guerra","guerrear"]],
    ["戻る","もどる",["to return (v.i.)","to come back"],["dar la vuelta","regresar"]],
    ["手伝う","てつだう",["to help"],["ayudar","asistir"]],
    ["手袋","てぶくろ",["glove(s)"],["guante"]],
    ["打つ","うつ",["to hit","to strike"],["golpear","pegar"]],
    ["払う","はらう",["to pay"],["pagar"]],
    ["承知","しょうち",["knowledge","awareness"],["concentimiento","aceptación"]],
    ["技術","ぎじゅつ",["technique","technology"],["técnica","habilidad"]],
    ["投げる","なげる",["to pitch","to cast away"],["tirar","arrojar"]],
    ["折る","おる",["to snap","to break"],["romper","doblar"]],
    ["折れる","おれる",["to break","to be folded"],["romper","doblarse"]],
    ["押し入れ","おしいれ",["closet"],["ropero","armario"]],
    ["招待","しょうたい",["invitation"],["invitación"]],
    ["拝見","はいけん",["seeing","looking at"],["ver"]],
    ["拾う","ひろう",["to pick up (something)","to find"],["reunir","juntar"]],
    ["指","ゆび",["finger"],["dedo","apuntar"]],
    ["指輪","ゆびわ",["(finger) ring"],["anillo"]],
    ["挨拶","あいさつ",["greeting","greetings"],["saludo"]],
    ["捕まえる","つかまえる",["to catch","to arrest"],["capturar","arrestar"]],
    ["捨てる","すてる",["throw away (trash)","dump"],["botar","tirar"]],
    ["探す","さがす",["to search","to seek"],["buscar (e.g. algo perdido, algo anhelado, algo necesario, al sospechoso de un crimen)","buscar (algo perdido"]],
    ["揺れる","ゆれる",["to shake","to sway"],["sacudir"]],
    ["支度","したく",["preparation","arrangements"],["preparar","hacer los preparativos"]],
    ["放送","ほうそう",["broadcasting","broadcast"],["emitir","transmitir"]],
    ["政治","せいじ",["politics"],["la política"]],
    ["故障","こしょう",["fault","trouble"],["dañado","falla"]],
    ["教会","きょうかい",["church"],["iglesia"]],
    ["教育","きょういく",["education"],["entrenamiento","educación"]],
    ["数学","すうがく",["mathematics"],["matemáticas"]],
    ["文化","ぶんか",["culture"],["cultura","civilización"]],
    ["文学","ぶんがく",["literature"],["literatura"]],
    ["文法","ぶんぽう",["grammar"],["gramática","sintaxis"]],
    ["新聞社","しんぶんしゃ",["newspaper company"],["compañia periodística"]],
    ["旅館","りょかん",["a Japanese inn"],["hostal","fonda (estilo japonesa)"]],
    ["日","ひ",["sun","sunshine"],["día"],[],1],
    ["日","にち",["Sunday"],["día del mes"],[],1],
    ["日記","にっき",["diary","journal"],["diario","bitácora"]],
    ["昔","むかし",["old days","past"],["antiguamente","antigüedad"]],
    ["星","ほし",["star"],["estrella","punto pequeño"]],
    ["是非","ぜひ",["certainly","by all means"],["ciertamente","sin falta"]],
    ["昼休み","ひるやすみ",["lunch break","noon recess"],["descanso de la tarde"]],
    ["昼間","ひるま",["daytime","during the day"],["día","durante el día"]],
    ["時代","じだい",["age","period"],["periodo","período"]],
    ["普通","ふつう",["common","usual"],["común","ordinario"]],
    ["景色","けしき",["scenery","landscape"],["paisaje"]],
    ["暖房","だんぼう",["heating"],["calefacción"]],
    ["暮れる","くれる",["to get dark","to come to an end"],["tornarse oscuro","finalizar"]],
    ["最も","もっとも",["most"],["más","extremadamente"]],
    ["最初","さいしょ",["beginning","first"],["comienzo","principio"]],
    ["最後","さいご",["last","end"],["último","fin"]],
    ["最近","さいきん",["recently","nowadays"],["lo más reciente","lo último"]],
    ["月","つき",["moon"],["luna"],["がつ"]],
    ["木綿","もめん",["cotton"],["algodón"]],
    ["林","はやし",["woods","forest"],["arboleda","soto"]],
    ["枝","えだ",["branch","twig"],["rama","bifurcación"]],
    ["柔らかい","やわらかい",["soft (in reference to texture)","tender"],["blando","blando"]],
    ["柔道","じゅうどう",["judo"],["judo","yudo"]],
    ["校長","こうちょう",["principal","headmaster"],["director de la escuela"]],
    ["格好","かっこう",["appearance","manner"],["figura","aspecto"]],
    ["案内","あんない",["guidance","leading (the way)"],["guiar","conducir a alguien"]],
    ["棚","たな",["shelves","rack"],["estante","repisa"]],
    ["森","もり",["forest"],["bosque"]],
    ["植える","うえる",["to plant"],["plantar","cultivar"]],
    ["楽しみ","たのしみ",["pleasure","joy"],["gozo","alegría"]],
    ["楽む","たのしむ",["to enjoy"],["disfrutar"]],
    ["様","よう",["way","manner"],["apariencia","aspecto"],[],1],
    ["様","さま",["Mr","Mrs"],["señor","don"],[],1],
    ["機会","きかい",["chance","opportunity"],["posibilidad","oportunidad"]],
    ["止む","やむ",["to cease","to stop"],["cesar","amainar"]],
    ["止める","やめる",["to end","to stop"],["parar","detener (algo)"],["とめる"]],
    ["正しい","ただしい",["correct"],["correcto","justo"]],
    ["正月","しょうがつ",["New Year","New Year's Day"],["Nuevo Año","Día de Año Nuevo"]],
    ["歯医者","はいしゃ",["dentist"],["dentista"]],
    ["歴史","れきし",["history"],["historia"]],
    ["残る","のこる",["to remain (v.i.)","to be left"],["quedar","dejar atrás"]],
    ["残念","ざんねん",["regret","regrettable"],["deplorable","mala suerte"]],
    ["比べる","くらべる",["to compare"],["comparar","calibrar"]],
    ["毛","け",["hair","fur"],["pelaje","vello"]],
    ["気","き",["spirit","mood"],["espíritu","mente"]],
    ["気分","きぶん",["feeling","mood"],["sentimiento","humor (e.g. buen humor, mal humor, etc.)"]],
    ["気持ち","きもち",["feeling","sensation"],["sentimiento","sensación"]],
    ["水泳","すいえい",["swimming"],["natación"]],
    ["水道","すいどう",["water service","water line"],["suministro de agua"]],
    ["汚れる","よごれる",["to become dirty"],["ensuciar"]],
    ["決して","けっして",["never"],["nunca","de ningún modo"]],
    ["決まる","きまる",["to be set","fixed (v.i.)"],["decidirse","arreglarse"]],
    ["決める","きめる",["to decide (v.t.)"],["decidir"]],
    ["汽車","きしゃ",["train (steam)"],["tren (de vapor)"]],
    ["沸かす","わかす",["to boil"],["hervir","calentar"]],
    ["沸く","わく",["to boil","to grow hot"],["hervir","excitarse"]],
    ["治る","なおる",["to get better","to recover from illness (v.i.)"],["curarse","sanar"]],
    ["泊まる","とまる",["to stay (over night) (v.i.)"],["quedarse en"]],
    ["法律","ほうりつ",["law"],["derecho"]],
    ["泣く","なく",["to cry"],["llorar","mojar"]],
    ["泥棒","どろぼう",["thief","burglar"],["ladrón"]],
    ["注射","ちゅうしゃ",["injection"],["inyección"]],
    ["注意","ちゅうい",["caution","attention"],["tener cuidado","prestar atención"]],
    ["浅い","あさい",["shallow","superficial"],["poco profundo","superficial"]],
    ["海岸","かいがん",["coast","seashore"],["costa"]],
    ["消しゴム","けしごむ",["eraser"],["goma de borrar"]],
    ["深い","ふかい",["deep","profound"],["profundo"]],
    ["済む","すむ",["to finish","to end"],["terminar de hacer (acabar)"]],
    ["港","みなと",["harbor","port"],["puerto","portuario"]],
    ["湖","みずうみ",["lake"],["lago"]],
    ["湯","ゆ",["hot water"],["agua caliente","fuente termal"]],
    ["準備","じゅんび",["preparation","arrangements"],["preparación","preparativo"]],
    ["滑る","すべる",["to slide","to slip"],["deslizarse","resbalar"]],
    ["漫画","まんが",["comic (book)","cartoon"],["comic","historieta"]],
    ["漬ける","つける",["to soak","to moisten"],["empapar","humedecer"]],
    ["濡れる","ぬれる",["to get wet"],["mojarse"]],
    ["火","ひ",["fire"],["fuego","flama"]],
    ["火事","かじ",["fire"],["fuego","conflagración"]],
    ["点","てん",["mark","score"],["punto","marca"]],
    ["点く","つく",["to be started","to be switched on"],["encenderse","coger fuego"]],
    ["為","ため",["good","advantage"],["hacer","ocurrir"]],
    ["無くなる","なくなる",["to disappear","to get lost"],["desaparecer","perderse"]],
    ["無理","むり",["unreasonable","impossible"],["a la fuerza","por la fuerza"]],
    ["焼く","やく",["to bake","to grill"],["hornear","asar"]],
    ["焼ける","やける",["to burn","to be roasted"],["estar celoso","tener envidia"]],
    ["熱","ねつ",["fever","temperature"],["calor","fiebre"]],
    ["熱心","ねっしん",["enthusiasm"],["celo","entusiasmo"]],
    ["片付ける","かたづける",["to (clean) tidy up (v.t.)","to put away"],["ordenar","poner en orden"]],
    ["特に","とくに",["particularly"],["particularmente","especialmente"]],
    ["特別","とくべつ",["special"],["especial"]],
    ["特急","とっきゅう",["limited express (train faster than an express)"],["tren expreso especial"]],
    ["珍しい","めずらしい",["unusual","rare"],["inusual","infrecuente"]],
    ["理由","りゆう",["reason"],["razón","pretexto"]],
    ["生きる","いきる",["to live"],["vivir","existir"]],
    ["生活","せいかつ",["life","living"],["vida (existencia diaria propia)","sustento"]],
    ["生産","せいさん",["production","manufacture"],["producción"]],
    ["産業","さんぎょう",["industry"],["industria"]],
    ["用","よう",["errand","task"],["uso","empleo"]],
    ["用事","ようじ",["business to take care of","tasks"],["tareas","cosas que hacer"]],
    ["用意","ようい",["preparation"],["hacer preparativos","preparar"]],
    ["田舎","いなか",["rural","countryside"],["rural","en el campo"]],
    ["申し上げる","もうしあげる",["(humble)to say","to tell"],["decir a alguien (lenguaje humilde)"]],
    ["申す","もうす",["-- extra-modest (humble) expression for 言う (いう) --"],["llamarse","decir"]],
    ["男性","だんせい",["man","male"],["sexo masculino","hombre"]],
    ["留守","るす",["absence","not at home"],["no estar en la casa"]],
    ["番組","ばんぐみ",["broadcast program"],["programa (ej. TV)"]],
    ["畳","たたみ",["tatami mat (Japanese straw mat)"],["tatami","estera (cubierta japonesa de paja en el piso)"],["じょう"]],
    ["痩せる","やせる",["to lose weight"],["adelgazar","perder peso"]],
    ["発音","はつおん",["pronunciation"],["pronunciación","pronunciar"]],
    ["皆","みな",["everyone"],["todo","todos"],["みんな"]],
    ["盗む","ぬすむ",["to steal","to rob"],["robar","hurtar"]],
    ["盛ん","さかん",["prosperous","active"],["popular"]],
    ["直す","なおす",["to correct (v.t.)","to fix"],["curar"]],
    ["直る","なおる",["to be fixed"],["curarse","sanar"]],
    ["相談","そうだん",["consultation","discussion"],["consultar","consejo"]],
    ["看護婦","かんごふ",["(female) nurse"],["(mujer) enfermera"]],
    ["真中","まんなか",["middle","center"],["medio","centro"]],
    ["真面目","まじめ",["diligent","serious"],["diligente","serio"]],
    ["眠い","ねむい",["sleepy","drowsy"],["soñoliento","amodorrado"]],
    ["眠る","ねむる",["to sleep"],["dormir (no necesariamente estando tumbado)"]],
    ["着物","きもの",["kimono","Japanese traditional dress"],["ropa"]],
    ["知らせる","しらせる",["to notify"],["notificar","aconsejar"]],
    ["石","いし",["stone"],["piedra"],[],1],
    ["石","こく",["koku","traditional unit of volume, approx. 180.4 litres"],["koku (medida de volumen)"],[],1],
    ["砂","すな",["sand"],["arena","gravilla"]],
    ["研究","けんきゅう",["study","research"],["estudio","investigación"]],
    ["研究室","けんきゅうしつ",["the professor's office","laboratory"],["laboratorio"]],
    ["確か","たしか",["if I remember correctly","certain"],["creo que","si no me equivoco"]],
    ["社会","しゃかい",["society"],["sociedad"]],
    ["社長","しゃちょう",["president of a company"],["presidente de la compañía","gerente"]],
    ["祈る","いのる",["to pray","to wish"],["rezar"]],
    ["祖母","そぼ",["grandmother"],["abuela"]],
    ["祖父","そふ",["grandfather"],["abuelo","abuelo"]],
    ["神社","じんじゃ",["Shinto shrine"],["Templo Sintoísta"]],
    ["科学","かがく",["science"],["ciencia"]],
    ["移る","うつる",["to move (from a house)","to transfer (from a department)"],["mudarse","transferir (departamento)"]],
    ["程","ほど",["degree","extent"],["grado","extensión"]],
    ["空く","あく",["to open","to become empty (vacant)"],["abrirse","quedarse abierto"],["すく"]],
    ["空気","くうき",["air","atmosphere"],["aire","atmósfera"]],
    ["空港","くうこう",["airport"],["aeropuerto"]],
    ["立てる","たてる",["to stand (something) up","to erect (something)"],["parar(algo)","erigir (algo)"]],
    ["競争","きょうそう",["competition","contest"],["competir","rivalizar"]],
    ["笑う","わらう",["to laugh","to smile"],["reír","sonreír"]],
    ["答","こたえ",["answer","response"],["solución","respuesta"]],
    ["簡単","かんたん",["simple"],["simple","sencillo"]],
    ["米","こめ",["uncooked rice"],["arroz no cocinado"],[],1],
    ["米","べい",["(United States of) America","USA"],["Estados Unidos"],[],1],
    ["糸","いと",["thread"],["hilo","hebra"]],
    ["約束","やくそく",["arrangement","appointment"],["promesa","cita"]],
    ["素晴らしい","すばらしい",["wonderful","terrific"],["maravilloso","espléndido"]],
    ["細かい","こまかい",["small","fine"],["pequeño","fino"]],
    ["紹介","しょうかい",["an introduction"],["presentación","presentar a alguien"]],
    ["終わり","おわり",["end"],["fin"]],
    ["経済","けいざい",["economics","finance"],["economía","negocios"]],
    ["経験","けいけん",["experience"],["experimentar","pasar por la experiencia de"]],
    ["絹","きぬ",["silk"],["seda"]],
    ["続く","つづく",["to be continued"],["que continuará"]],
    ["続ける","つづける",["to continue","to keep up"],["continuar","proseguir"]],
    ["線","せん",["line","wire"],["línea","cable"]],
    ["美しい","うつくしい",["beautiful","lovely"],["hermoso","bello"]],
    ["美術館","びじゅつかん",["art gallery","art museum"],["galería de arte","museo de arte"]],
    ["習慣","しゅうかん",["custom (in reference to culture)"],["costumbre","hábito"]],
    ["翻訳","ほんやく",["translation"],["traducción","descifrado"]],
    ["考える","かんがえる",["to think (about)","to consider"],["pensar","considerar"]],
    ["聞こえる","きこえる",["to be heard","to be audible"],["escucharse","oírse"]],
    ["育てる","そだてる",["to raise (v.t.)","to bring up"],["criar","educar"]],
    ["背中","せなか",["back (of body)"],["espalda"]],
    ["腕","うで",["arm (in reference to body)"],["brazo","habilidad"]],
    ["自由","じゆう",["freedom"],["libertad","como te plazca"]],
    ["致す","いたす",["-- extra-modest expression for する --"],["hacer"]],
    ["興味","きょうみ",["interest (in something)"],["interés (en algo)"]],
    ["舟","ふね",["ship","boat"],["bote","barco"]],
    ["花見","はなみ",["cherry-blossom viewing"],["vista de la flor","ver los cerezos florecer"]],
    ["苦い","にがい",["bitter"],["amargo"]],
    ["草","くさ",["grass"],["hierba","planta"]],
    ["落す","おとす",["to drop","to lose"],["caer","perder"]],
    ["落る","おちる",["to fall","to drop"],["caer","derrumbar"]],
    ["葉","は",["leaf"],["hoja","contador de cosas planas"]],
    ["虫","むし",["insect"],["insecto","bicho"]],
    ["血","ち",["blood"],["sangre","consanguinidad"]],
    ["行う","おこなう",["to carry out","to conduct (typically used in written language)"],["ejecutar","hacer"]],
    ["表","おもて",["surface","front"],["frente","superficie"],[],1],
    ["表","ひょう",["table","chart"],["lista"],[],1],
    ["裏","うら",["reverse side","back"],["reverso","opuesto"]],
    ["複雑","ふくざつ",["complexity","complication"],["complejidad","complicación"]],
    ["褒める","ほめる",["to praise","to say nice things"],["alabar","admirar"]],
    ["西洋","せいよう",["the West","Western countries"],["occidente","países occidentales"]],
    ["見える","みえる",["to be visible","-- polite verb meaning 来る (くる) --"],["verse","estar a la vista"]],
    ["見つかる","みつかる",["to be found (v.i.)","to be discovered"],["ser encontrado","ser visto"]],
    ["見つける","みつける",["to discover","to find (v.t.)"],["descubrir","encontrar (e.g. un error en un libro)"]],
    ["見物","けんぶつ",["sightseeing"],["recurrido turístico"]],
    ["規則","きそく",["rule","regulation"],["regla"]],
    ["親","おや",["a parent"],["padre","madre"]],
    ["親切","しんせつ",["kindness"],["amable"]],
    ["触る","さわる",["to touch","to feel"],["tocar"]],
    ["計画","けいかく",["plan","project"],["plan","proyecto"]],
    ["訪ねる","たずねる",["to visit"],["visitar"]],
    ["訳","わけ",["reason","explanation"],["traducir","razón"]],
    ["試合","しあい",["match","game"],["juego","contienda"]],
    ["試験","しけん",["an exam"],["examen","prueba"]],
    ["説明","せつめい",["explanation"],["explicar","aclarar"]],
    ["課長","かちょう",["section manager"],["director de sección","jefe de sección"]],
    ["調べる","しらべる",["to check","to look up"],["investigar","averiguar"]],
    ["講堂","こうどう",["auditorium"],["auditorio"]],
    ["講義","こうぎ",["a lecture"],["dar un curso","dar la lección"]],
    ["謝る","あやまる",["to apologize"],["disculparse"]],
    ["警察","けいさつ",["police","police station"],["policía"]],
    ["負ける","まける",["to lose (a game) (v.i.)","to be defeated"],["perder","ser derrotado"]],
    ["貿易","ぼうえき",["trade"],["comercio"]],
    ["贈り物","おくりもの",["a gift","a present"],["regalo","obsequio"]],
    ["赤ちゃん","あかちゃん",["baby","infant"],["bebe","criatura"]],
    ["赤ん坊","あかんぼう",["baby"],["bebé"]],
    ["起こす","おこす",["to wake (someone) up"],["levantar","causar"]],
    ["趣味","しゅみ",["hobby","pastime"],["hobby","gusto"]],
    ["足す","たす",["to add (numbers)"],["sumar (números)"]],
    ["足りる","たりる",["to be sufficient","to be enough"],["bastar","ser suficiente"]],
    ["踊り","おどり",["dance"],["danza"]],
    ["踊る","おどる",["to dance"],["bailar","danzar"]],
    ["踏む","ふむ",["to step on","to tread on"],["pisar"]],
    ["輸入","ゆにゅう",["import"],["importación","artículo importado"]],
    ["輸出","ゆしゅつ",["export","exportation"],["exportación","exportar"]],
    ["辞典","じてん",["encyclopedia","reference book"],["diccionario"]],
    ["込む","こむ",["to be crowded"],["llenarse"]],
    ["迎える","むかえる",["to welcome","to meet"],["recoger (personas)"]],
    ["近所","きんじょ",["neighborhood"],["vecindario"]],
    ["返事","へんじ",["reply","answer"],["respuesta","contestación"]],
    ["退院","たいいん",["leaving hospital","discharge from hospital"],["alta de un hospital"]],
    ["送る","おくる",["to send","to dispatch"],["enviar (cosas)","despachar"]],
    ["逃げる","にげる",["to escape","to run away"],["escapar","huir"]],
    ["途中","とちゅう",["on the way","midway"],["de camino","a mitad de camino"]],
    ["通う","かよう",["to go back and forth","to commute"],["transportar","conmutar"]],
    ["通り","とおり",["~ Street","~ Avenue"],["avenida","calle"],[],1],
    ["通り","どおり",["in accordance with","following"],["de acuerdo con","según"],[],1],
    ["通る","とおる",["to pass (by)","to go through"],["pasar por","aprobarse"]],
    ["連れる","つれる",["to lead","to take (a person)"],["guiar","acompañar"]],
    ["連絡","れんらく",["communication","contact"],["comunicar","contactar"]],
    ["進む","すすむ",["to advance","to proceed"],["progresar","avanzar"]],
    ["遅れる","おくれる",["to (be) become late"],["llegar tarde","llegar tarde"]],
    ["遊び","あそび",["play"],["juego","visita"]],
    ["運ぶ","はこぶ",["to transport","to carry"],["transportar"]],
    ["運動","うんどう",["exercise","physical training"],["ejercicio","movimiento"]],
    ["運転","うんてん",["operation (of a machine)","running"],["operación","movimiento"]],
    ["運転手","うんてんしゅ",["driver (by occupation)"],["chofer","conductor"]],
    ["過ぎる","すぎる",["to exceed","to go beyond"],["pasar","ir más allá"]],
    ["道具","どうぐ",["tool"],["herramienta","implemento"]],
    ["遠く","とおく",["far away","distant"],["en la lejanía"]],
    ["遠慮","えんりょ",["reserve","constraint"],["abstenerse de","excusarse de"]],
    ["適当","てきとう",["fitness","suitability"],["al azar","al buen tuntún"]],
    ["選ぶ","えらぶ",["to choose","to select"],["escoger","seleccionar"]],
    ["邪魔","じゃま",["hindrance","intrusion"],["obstáculo","estorbo"]],
    ["郊外","こうがい",["suburb","outskirts"],["suburbios","afueras"]],
    ["部長","ぶちょう",["department (division) manager"],["jefe de área"]],
    ["都","と",["metropolitan"],["metrópoli","capital"],["みやこ"]],
    ["都合","つごう",["circumstances","convenience"],["circunstancias","condición"]],
    ["釣る","つる",["to fish"],["pescar"]],
    ["鏡","かがみ",["mirror"],["espejo","espéculo"]],
    ["間","あいだ",["space","interval"],["espacio","intervalo"],["ま","かん"]],
    ["間に合う","まにあう",["to be in time for"],["estar a tiempo para"]],
    ["間違える","まちがえる",["to make a mistake"],["equivocar","errar"]],
    ["関係","かんけい",["relation(ship)","connection"],["estar relacionado con","tener que ver con"]],
    ["隅","すみ",["corner"],["esquina","rincón"]],
    ["随分","ずいぶん",["extremely"],["extremadamente"]],
    ["集まる","あつまる",["to gather (v.i.)","to collect"],["acopiar","recolectar"]],
    ["集める","あつめる",["to collect","to gather (v.t.)"],["recolectar","ensamblar"]],
    ["雲","くも",["cloud"],["nube"]],
    ["電報","でんぽう",["telegram"],["telegrama"]],
    ["電灯","でんとう",["electric light"],["luz eléctrica"]],
    ["非常に","ひじょうに",["extremely","very"],["excesivo","extremadamente"]],
    ["音","おと",["sound","note"],["sonido","ruido"],["おん","ね"]],
    ["頑張る","がんばる",["to try one's best","to try hard"],["persistir","insistir"]],
    ["飛行場","ひこうじょう",["airport"],["aeropuerto"]],
    ["食事","しょくじ",["meal (e.g. lunch, dinner)"],["comida"]],
    ["食料品","しょくりょうひん",["foodstuff","groceries"],["comestibles","víveres"]],
    ["飾る","かざる",["to decorate","to adorn"],["decorar","ornamentar"]],
    ["首","くび",["neck"],["cuello","principio"]],
    ["駐車場","ちゅうしゃじょう",["parking lot"],["estacionamiento","aparcamiento"]],
    ["騒ぐ","さわぐ",["to make noise","to clamor"],["hacer escándalo","hacer bulla"]],
    ["驚く","おどろく",["to be surprised","to be astonished"],["ser sorprendido"]],
    ["高校","こうこう",["high school","senior high school"],["instituto","(am) (escuela) preparatoria"]],
    ["高校生","こうこうせい",["high school student"],["estudiante de bachillerato","estudiante de instituto"]],
    ["髪","かみ",["hair"],["pelo","cabello"]],
    ["鳴る","なる",["to sound","to ring (v.i.)"],["sonar","repicar"]]
  ],
  kanji: [
    ["不",["negative","non-","bad"],["prefijo negativo: in-","des-"],["フ","ブ"],[]],
    ["世",["generation","world","society"],["generación","mundo","edad"],["セイ","セ","ソウ"],["よ"]],
    ["主",["lord","chief","master"],["señor","jefe","dueño"],["シュ","ス","シュウ"],["ぬし","おも","あるじ"]],
    ["事",["matter","thing","fact"],["cosa","hecho","asunto"],["ジ","ズ"],["こと","つか.う","つか.える"]],
    ["京",["capital","10**16"],["capital"],["キョウ","ケイ","キン"],["みやこ"]],
    ["仕",["attend","doing","official"],["trabajo","servir","asistir"],["シ","ジ"],["つか.える"]],
    ["代",["substitute","change","convert"],["generación","reinado","sustituir"],["ダイ","タイ"],["か.わる","かわ.る","かわ.り","か.わり","-がわ.り"]],
    ["以",["by means of","because","in view of"],["además de","más que"],["イ"],["もっ.て"]],
    ["会",["meeting","meet","party"],["asociación","reunión","encontrarse con"],["カイ","エ"],["あ.う","あ.わせる","あつ.まる"]],
    ["住",["dwell","reside","live"],["residir","vivir","habitar"],["ジュウ","ヂュウ","チュウ"],["す.む","す.まう","-ず.まい"]],
    ["体",["body","substance","object"],["cuerpo","forma"],["タイ","テイ"],["からだ","かたち"]],
    ["作",["make","production","prepare"],["hacer","construir","fabricar"],["サク","サ"],["つく.る","つく.り","-づく.り"]],
    ["使",["use","send on a mission","order"],["usar","manejar","emplear"],["シ"],["つか.う","つか.い","-つか.い","-づか.い"]],
    ["借",["borrow","rent"],["deuda","pedir prestado","alquilar"],["シャク"],["か.りる"]],
    ["元",["beginning","former time","origin"],["comienzo","principio","origen"],["ゲン","ガン"],["もと"]],
    ["兄",["elder brother","big brother"],["hermano mayor"],["ケイ","キョウ"],["あに"]],
    ["公",["public","prince","official"],["público","imparcial","oficial"],["コウ","ク"],["おおやけ"]],
    ["写",["copy","be photographed","describe"],["copiar","imitar","fotografiar"],["シャ","ジャ"],["うつ.す","うつ.る","うつ-","うつ.し"]],
    ["冬",["winter"],["invierno"],["トウ"],["ふゆ"]],
    ["切",["cut","cutoff","be sharp"],["cortar","urgente","apremiante"],["セツ","サイ"],["き.る","-き.る","き.り","-き.り","-ぎ.り"]],
    ["別",["separate","branch off","diverge"],["separar","aparte","distinto"],["ベツ"],["わか.れる","わ.ける"]],
    ["力",["power","strength","strong"],["potencia","poder","fuerza"],["リョク","リキ","リイ"],["ちから"]],
    ["勉",["exertion","endeavour","encourage"],["esforzarse","ejercitarse"],["ベン"],["つと.める"]],
    ["動",["move","motion","change"],["mover","movimiento","moverse"],["ドウ"],["うご.く","うご.かす"]],
    ["医",["doctor","medicine"],["doctor","médico","medicina"],["イ"],["い.やす","い.する","くすし"]],
    ["去",["gone","past","quit"],["pasado","ido","dejar"],["キョ","コ"],["さ.る","-さ.る"]],
    ["口",["mouth"],["boca","orificio","apertura"],["コウ","ク"],["くち"]],
    ["古",["old"],["viejo","antiguo","desgastar"],["コ"],["ふる.い","ふる-","-ふる.す"]],
    ["台",["pedestal","a stand","counter for machines and vehicles"],["estante","banco","tribuna"],["ダイ","タイ"],["うてな","われ","つかさ"]],
    ["同",["same","agree","equal"],["mismo","igual","compañero"],["ドウ"],["おな.じ"]],
    ["味",["flavor","taste"],["sabor","gusto","experiencia"],["ミ"],["あじ","あじ.わう"]],
    ["品",["goods","refinement","dignity"],["producto","artículo","bienes"],["ヒン","ホン"],["しな"]],
    ["員",["employee","member","number"],["empleado","miembro","personal"],["イン"],[]],
    ["問",["question","ask","problem"],["duda","pregunta","problema"],["モン"],["と.う","と.い","とん"]],
    ["図",["map","drawing","plan"],["dibujo","ilustración","consulta"],["ズ","ト"],["え","はか.る"]],
    ["地",["ground","earth"],["suelo","tierra","terreno"],["チ","ジ"],[]],
    ["堂",["public chamber","hall"],["templo","salón","vestíbulo"],["ドウ"],[]],
    ["場",["location","place"],["lugar","situación","momento"],["ジョウ","チョウ"],["ば"]],
    ["売",["sell"],["vender","ensanchar","propagar"],["バイ"],["う.る","う.れる"]],
    ["夏",["summer"],["verano"],["カ","ガ","ゲ"],["なつ"]],
    ["夕",["evening"],["tarde","noche"],["セキ"],["ゆう"]],
    ["多",["many","frequent","much"],["abundante","mucho"],["タ"],["おお.い","まさ.に","まさ.る"]],
    ["夜",["night","evening"],["noche","tarde"],["ヤ"],["よ","よる"]],
    ["妹",["younger sister"],["hermana menor"],["マイ"],["いもうと"]],
    ["姉",["elder sister"],["hermana mayor"],["シ"],["あね","はは"]],
    ["始",["commence","begin"],["comenzar","empezar","empezar (trans.)"],["シ"],["はじ.める","-はじ.める","はじ.まる"]],
    ["字",["character","letter","word"],["carácter","letra","palabra"],["ジ"],["あざ","あざな","-な"]],
    ["安",["relax","cheap","low"],["barato","tranquilo","pacífico"],["アン"],["やす.い","やす.まる","やす","やす.らか"]],
    ["室",["room","apartment","chamber"],["habitación","cuarto","caverna"],["シツ"],["むろ"]],
    ["家",["house","home","family"],["casa","hogar","especialista"],["カ","ケ"],["いえ","や","うち"]],
    ["少",["few","little"],["poco","pequeño","un poco"],["ショウ"],["すく.ない","すこ.し"]],
    ["屋",["roof","house","shop"],["casa","tejado","tienda"],["オク"],["や"]],
    ["工",["craft","construction","katakana e radical (no. 48)"],["construcción","fabricación","obrero"],["コウ","ク","グ"],[]],
    ["帰",["homecoming","arrive at","lead to"],["regreso","vuelta","retorno"],["キ"],["かえ.る","かえ.す","おく.る","とつ.ぐ"]],
    ["広",["wide","broad","spacious"],["amplio","ancho","espacioso"],["コウ"],["ひろ.い","ひろ.まる","ひろ.める","ひろ.がる","ひろ.げる"]],
    ["店",["store","shop"],["tienda","establecimiento"],["テン"],["みせ","たな"]],
    ["度",["degrees","occurrence","time"],["grado","vez","veces"],["ド","ト","タク"],["たび","-た.い"]],
    ["建",["build"],["construir","edificar","levantarse"],["ケン","コン"],["た.てる","た.て","-だ.て","た.つ"]],
    ["弟",["younger brother","faithful service to elders"],["hermano menor"],["テイ","ダイ","デ"],["おとうと"]],
    ["強",["strong"],["fuerte","coacción","poderoso"],["キョウ","ゴウ"],["つよ.い","つよ.まる","つよ.める","し.いる","こわ.い"]],
    ["待",["wait","depend on"],["esperar","aguardar"],["タイ"],["ま.つ","-ま.ち"]],
    ["心",["heart","mind","spirit"],["corazón","centro"],["シン"],["こころ","-ごころ"]],
    ["思",["think"],["pensar","considerar"],["シ"],["おも.う","おもえら.く","おぼ.す"]],
    ["急",["hurry","emergency","sudden"],["prisa","urgencia","apresurarse"],["キュウ"],["いそ.ぐ","いそ.ぎ","せ.く"]],
    ["悪",["bad","vice","rascal"],["malo","incorrecto","equivocado"],["アク","オ"],["わる.い","わる-","あ.し","にく.い","-にく.い"]],
    ["意",["idea","mind","heart"],["idea","sentimiento","razón"],["イ"],[]],
    ["手",["hand"],["mano"],["シュ","ズ"],["て","て-","-て","た-"]],
    ["持",["hold","have"],["duración","propiedad","cargo"],["ジ"],["も.つ","-も.ち","も.てる"]],
    ["教",["teach","faith","doctrine"],["educación","enseñanza","enseñar"],["キョウ"],["おし.える","おそ.わる"]],
    ["文",["sentence","literature","style"],["letras","literatura"],["ブン","モン"],["ふみ","あや"]],
    ["料",["fee","materials"],["material","precio"],["リョウ"],[]],
    ["新",["new"],["nuevo","fresco"],["シン"],["あたら.しい","あら.た","あら-","にい-"]],
    ["方",["direction","person","alternative"],["dirección","lado","cuadrado"],["ホウ"],["かた","-かた","-がた"]],
    ["旅",["trip","travel"],["viaje","trayecto","excursión"],["リョ"],["たび"]],
    ["族",["tribe","family"],["tribu","familia"],["ゾク"],[]],
    ["早",["early","fast"],["temprano","rápido","pronto"],["ソウ","サッ"],["はや.い","はや","はや-","はや.まる","はや.める"]],
    ["明",["bright","light"],["luz","brillo","claridad"],["メイ","ミョウ","ミン"],["あ.かり","あか.るい","あか.るむ","あか.らむ","あき.らか"]],
    ["映",["reflect","reflection","projection"],["reflejo","reflexión","reflejar"],["エイ"],["うつ.る","うつ.す","は.える","-ば.え"]],
    ["春",["springtime","spring (season)"],["primavera","comienzo del año","tiempos de juventud"],["シュン"],["はる"]],
    ["昼",["daytime","noon"],["día","mediodía"],["チュウ"],["ひる"]],
    ["曜",["weekday"],["día de la semana","brillar","resplandecer"],["ヨウ"],[]],
    ["有",["possess","have","exist"],["existir","poseer","tener"],["ユウ","ウ"],["あ.る"]],
    ["服",["clothing","admit","obey"],["ropa","admitir","obedecer"],["フク"],[]],
    ["朝",["morning","dynasty","regime"],["mañana","amanecer","corte imperial"],["チョウ"],["あさ"]],
    ["業",["business","vocation","arts"],["negocio","industria","trabajo"],["ギョウ","ゴウ"],["わざ"]],
    ["楽",["music","comfort","ease"],["música","divertido","fácil"],["ガク","ラク","ゴウ"],["たの.しい","たの.しむ","この.む"]],
    ["歌",["song","sing"],["canción","cantar"],["カ"],["うた","うた.う"]],
    ["止",["stop","halt"],["parar","cesar","dejar de hacer"],["シ"],["と.まる","-ど.まり","と.める","-と.める","-ど.め"]],
    ["正",["correct","justice","righteous"],["correcto","justo","arreglar"],["セイ","ショウ"],["ただ.しい","ただ.す","まさ","まさ.に"]],
    ["歩",["walk","counter for steps"],["camino","caminar","razón"],["ホ","ブ","フ"],["ある.く","あゆ.む"]],
    ["死",["death","die"],["muerte","morir"],["シ"],["し.ぬ","し.に-"]],
    ["注",["pour","irrigate","shed (tears)"],["derramar","verter","regar"],["チュウ"],["そそ.ぐ","さ.す","つ.ぐ"]],
    ["洋",["ocean","sea","foreign"],["océano","de estilo occidental","cada una de las dos mitades del mundo"],["ヨウ"],[]],
    ["海",["sea","ocean"],["mar","océano","playa"],["カイ"],["うみ"]],
    ["漢",["Sino-","China"],["antigua región de China","China","hombre"],["カン"],[]],
    ["牛",["cow"],["vaca","ganado"],["ギュウ"],["うし"]],
    ["物",["thing","object","matter"],["cosa","objeto","materia"],["ブツ","モツ"],["もの","もの-"]],
    ["特",["special"],["especial"],["トク"],[]],
    ["犬",["dog"],["perro"],["ケン"],["いぬ","いぬ-"]],
    ["理",["logic","arrangement","reason"],["lógica","razón","preparar"],["リ"],["ことわり"]],
    ["用",["utilize","business","service"],["uso","empleo","trabajo"],["ヨウ"],["もち.いる"]],
    ["田",["rice field","rice paddy"],["campo de arroz","arrozal"],["デン"],["た"]],
    ["町",["town","village","block"],["pueblo","ciudad","bloque"],["チョウ"],["まち"]],
    ["画",["brush-stroke","picture"],["dibujo","trazo","puntuar"],["ガ","カク","エ"],["えが.く","かく.する","かぎ.る","はかりごと","はか.る"]],
    ["界",["world","boundary"],["borde","frontera","extensión"],["カイ"],[]],
    ["病",["ill","sick"],["enfermedad","caer enfermo"],["ビョウ","ヘイ"],["や.む","-や.み","やまい"]],
    ["発",["departure","discharge","publish"],["abrir","exponer","suceder"],["ハツ","ホツ"],["た.つ","あば.く","おこ.る","つか.わす","はな.つ"]],
    ["目",["eye","class","look"],["ojo","mirada","percepción"],["モク","ボク"],["め","-め","ま-"]],
    ["真",["true","reality","Buddhist sect"],["verdad","realidad","puro"],["シン"],["ま","ま-","まこと"]],
    ["着",["don","arrive","wear"],["usar","llevar puesto","vestir"],["チャク","ジャク"],["き.る","き.せる","つ.く","つ.ける"]],
    ["知",["know","wisdom"],["conocer","saber","entender"],["チ"],["し.る","し.らせる"]],
    ["研",["polish","study of","sharpen"],["estudio","afilar","pulir"],["ケン"],["と.ぐ"]],
    ["社",["company","firm","office"],["compañía","asociación","sociedad"],["シャ"],["やしろ"]],
    ["私",["private","I","me"],["yo","privado","secreto"],["シ"],["わたくし","わたし"]],
    ["秋",["autumn"],["otoño"],["シュウ"],["あき","とき"]],
    ["究",["research","study"],["estudio","investigación","profundización"],["キュウ","ク"],["きわ.める"]],
    ["空",["empty","sky","void"],["cielo","atmósfera","vacío"],["クウ"],["そら","あ.く","あ.き","あ.ける","から"]],
    ["立",["stand up","rise","set up"],["levantarse","alzarse","ponerse en pie"],["リツ","リュウ","リットル"],["た.つ","-た.つ","た.ち-","た.てる","-た.てる"]],
    ["答",["solution","answer"],["solución","respuesta","contestar"],["トウ"],["こた.える","こた.え"]],
    ["紙",["paper"],["papel","periódico"],["シ"],["かみ"]],
    ["終",["end","finish"],["fin","final","terminar"],["シュウ"],["お.わる","-お.わる","おわ.る","お.える","つい"]],
    ["習",["learn"],["aprender","estudiar"],["シュウ","ジュ"],["なら.う","なら.い"]],
    ["考",["consider","think over"],["idea","pensar","investigar"],["コウ"],["かんが.える","かんが.え"]],
    ["者",["someone","person"],["persona"],["シャ"],["もの"]],
    ["肉",["meat"],["carne"],["ニク"],["しし"]],
    ["自",["oneself"],["uno mismo","por sí mismo","auto-"],["ジ","シ"],["みずか.ら","おの.ずから","おの.ずと"]],
    ["色",["color"],["color","aspecto"],["ショク","シキ"],["いろ"]],
    ["花",["flower"],["flor"],["カ","ケ"],["はな"]],
    ["英",["England","English","hero"],["Inglaterra","excelente"],["エイ"],["はなぶさ"]],
    ["茶",["tea"],["hoja de té","té"],["チャ","サ"],[]],
    ["親",["parent","intimacy","relative"],["padre","madre","familiares"],["シン"],["おや","おや-","した.しい","した.しむ"]],
    ["言",["say","word"],["palabras","decir"],["ゲン","ゴン"],["い.う","こと"]],
    ["計",["plot","plan","scheme"],["medida","cuenta","contar"],["ケイ"],["はか.る","はか.らう"]],
    ["試",["test","try","attempt"],["prueba","ensayo","experimento"],["シ"],["こころ.みる","ため.す"]],
    ["買",["buy"],["comprar"],["バイ"],["か.う"]],
    ["貸",["lend"],["préstamo","prestar","alquilar"],["タイ"],["か.す","か.し-","かし-"]],
    ["質",["substance","quality","matter"],["substancia","contenido","simplicidad"],["シツ","シチ","チ"],["たち","ただ.す","もと","わりふ"]],
    ["赤",["red"],["rojo","enrojecer","enrojecerse"],["セキ","シャク"],["あか","あか-","あか.い","あか.らむ","あか.らめる"]],
    ["走",["run"],["correr","escapar","huir"],["ソウ"],["はし.る"]],
    ["起",["rouse","wake up","get up"],["despertar","levantarse","comenzar"],["キ"],["お.きる","お.こる","お.こす","おこ.す","た.つ"]],
    ["足",["leg","foot","be sufficient"],["pierna","pie","ser suficiente"],["ソク"],["あし","た.りる","た.る","た.す"]],
    ["転",["revolve","turn around","change"],["cambiar","girar","rodar"],["テン"],["ころ.がる","ころ.げる","ころ.がす","ころ.ぶ","まろ.ぶ"]],
    ["近",["near","early","akin"],["cerca","cercano"],["キン","コン"],["ちか.い"]],
    ["送",["escort","send"],["enviar","remitir","expedir"],["ソウ"],["おく.る"]],
    ["通",["traffic","pass through","avenue"],["atravesar","traspasar","hacer saber"],["ツウ","ツ"],["とお.る","とお.り","-とお.り","-どお.り","とお.す"]],
    ["週",["week"],["semana"],["シュウ"],[]],
    ["運",["carry","luck","destiny"],["suerte","destino","transportar"],["ウン"],["はこ.ぶ"]],
    ["道",["road-way","street","district"],["camino","razón","modo"],["ドウ","トウ"],["みち","いう"]],
    ["重",["heavy","important","esteem"],["pesado","importante","apilar"],["ジュウ","チョウ"],["え","おも.い","おも.り","おも.なう","かさ.ねる"]],
    ["野",["plains","field","rustic"],["campo","llano","extensión"],["ヤ","ショ"],["の","の-"]],
    ["銀",["silver"],["plata"],["ギン"],["しろがね"]],
    ["開",["open","unfold","unseal"],["abrir","desdoblar","dar comienzo"],["カイ"],["ひら.く","ひら.き","-びら.き","ひら.ける","あ.く"]],
    ["院",["Inst.","institution","temple"],["institución","templo","hospital"],["イン"],[]],
    ["集",["gather","meet","congregate"],["reunir","coleccionar","reunirse"],["シュウ"],["あつ.まる","あつ.める","つど.う"]],
    ["青",["blue","green"],["azul","verde","pálido"],["セイ","ショウ"],["あお","あお-","あお.い"]],
    ["音",["sound","noise"],["sonido","ruido"],["オン","イン","-ノン"],["おと","ね"]],
    ["題",["topic","subject"],["objeto","tema","materia"],["ダイ"],[]],
    ["風",["wind","air","style"],["viento","aire","hábito"],["フウ","フ"],["かぜ","かざ-"]],
    ["飯",["meal","boiled rice"],["comida","arroz cocido"],["ハン"],["めし"]],
    ["飲",["drink","smoke","take"],["beber"],["イン","オン"],["の.む","-の.み"]],
    ["館",["building","mansion","large building"],["edificio","mansión"],["カン"],["やかた","たて"]],
    ["駅",["station"],["estación"],["エキ"],[]],
    ["験",["verification","effect","testing"],["prueba","intento","efecto"],["ケン","ゲン"],["あかし","しるし","ため.す","ためし"]],
    ["魚",["fish"],["pez","pescado"],["ギョ"],["うお","さかな","-ざかな"]],
    ["鳥",["bird","chicken"],["pájaro","ave"],["チョウ"],["とり"]],
    ["黒",["black"],["negro","maldad"],["コク"],["くろ","くろ.ずむ","くろ.い"]],
    ["嘘",["lie","falsehood"],["mentira","falsedad"],["キョ","コ"],["うそ","ふ.く"]],
    ["喉",["throat","voice"],["garganta"],["コウ"],["のど"]],
    ["噛",["chew","bite","gnaw"],[],["コウ","ゴウ"],["か.む","か.じる"]],
    ["痩",["get thin"],[],["ソウ","チュウ","シュウ"],["や.せる"]],
    ["坊",["boy","priest's residence","priest"],["chico","muchacho","sacerdote"],["ボウ","ボッ"],[]],
    ["匂",["fragrant","stink","glow"],["oler","fragante","oloroso"],[],["にお.う","にお.い","にお.わせる"]],
    ["挨",["approach","draw near","push open"],["empujar","acercarse"],["アイ"],["ひら.く"]],
    ["拶",["be imminent","draw close"],["acercarse","ser inminente"],["サツ"],["せま.る"]],
    ["噌",["boisterous"],[],["ソウ","ショウ","ソ"],["かまびす.しい"]],
    ["凄",["uncanny","weird","threatening"],[],["セイ","サイ"],["さむ.い","すご.い","すさ.まじい"]],
    ["叱",["scold","reprove"],["regañina","reproche","regañar"],["シツ","シチ","カ"],["しか.る"]],
    ["濡",["get wet","damp","make love"],[],["ジュ","ニュ"],["ぬれ.る","ぬら.す","ぬ.れる","ぬ.らす","うるお.い"]],
    ["頃",["time","about","toward"],["tiempo","aproximadamente","hacia"],["ケイ","キョウ"],["ころ","ごろ","しばら.く"]]
  ]
});
