/* Banco N5: palabras [escritura, lectura, inglés, español, otras lecturas válidas, 1 = ambigua,
   1 = suele escribirse en kana] y kanjis [carácter, inglés, español, on, kun].
   Formato y uso en bank/bank.js. */
BANK.add("N5", {
  words: [
    ["お兄さん","おにいさん",["(someone else's) older brother (formal)"],["hermano mayor","(vocativo) joven"]],
    ["お姉さん","おねえさん",["older sister (formal)"],["hermana mayor"]],
    ["お弁当","おべんとう",["a boxed lunch"],["o-bento","almuerzo portátil"]],
    ["お手洗い","おてあらい",["toilet","restroom"],["retrete","baño"]],
    ["お母さん","おかあさん",["mother (formal)"],["madre"]],
    ["お父さん","おとうさん",["father (formal)"],["padre"]],
    ["お皿","おさら",["plate","dish"],["plato","platillo"]],
    ["お腹","おなか",["stomach"],["estómago","vientre"]],
    ["お茶","おちゃ",["(green) tea"],["té (verde)"]],
    ["お菓子","おかし",["confections","sweets"],["dulces","golosinas"]],
    ["お酒","おさけ",["sake","alcohol"],["sake"]],
    ["お金","おかね",["money"],["dinero"]],
    ["お風呂","おふろ",["a bath"],["baño"]],
    ["さ来年","さらいねん",["year after next"],["dentro de dos años"]],
    ["一","いち",["one"],["uno"],["ひと"]],
    ["一つ","ひとつ",["one thing"],["uno"]],
    ["一人","ひとり",["one person"],["una persona"]],
    ["一日","いちにち",["one day (duration)"],["primer día del mes"],["ついたち"]],
    ["一昨日","おととい",["the day before yesterday"],["anteayer","antier"]],
    ["一月","ひとつき",["one month"],["un mes"],[],1],
    ["一月","いちがつ",["January"],["enero","Enero"],[],1],
    ["一番","いちばん",["best (most)","first"],["(el) mejor","(el) número uno"]],
    ["一緒","いっしょ",["together"],["juntos","encuentro"]],
    ["丁度","ちょうど",["just","right"],["exactamente","precisamente"],[],0,1],
    ["七","しち",["seven"],["siete","7"],["なな"]],
    ["七つ","ななつ",["seven things"],["7","siete"]],
    ["七日","なのか",["seven days","seventh day (of the month)"],["séptimo día del año"]],
    ["万","まん",["ten thousand"],["diez mil","muchos"]],
    ["万年筆","まんねんひつ",["fountain pen"],["pluma estilográfica"]],
    ["丈夫","じょうぶ",["strong","solid"],["saludable","fuerte"]],
    ["三","さん",["three"],["3","tres (usado en documentos legales)"],["み"]],
    ["三つ","みっつ",["three things"],["3","tres"]],
    ["三日","みっか",["three days","third day of the month"],["tercer día del mes"]],
    ["上","うえ",["above (up, top, etc.)","over"],["encima","arriba"]],
    ["上げる","あげる",["to raise","to lift"],["elevar","levantar"]],
    ["上手","じょうず",["be good at","skillful"],["nivel","hábil"]],
    ["上着","うわぎ",["coat","jacket"],["abrigo","túnica"]],
    ["下","した",["under","below"],["debajo"],["もと"]],
    ["下さい","ください",["(with te-form verb) please do for me"],["por favor"],[],0,1],
    ["下手","へた",["unskillful","poor"],["torpe"]],
    ["両親","りょうしん",["parents (lit., both parents)"],["padres (los propios)","ambos padres"]],
    ["並ぶ","ならぶ",["to line up","to stand in a line (v.i.)"],["poner en fila"]],
    ["並べる","ならべる",["to put (things) side by side","to line up"],["alinear"]],
    ["中","なか",["inside","middle"],["adentro","dentro"],["ちゅう"]],
    ["丸い","まるい",["round","circular"],["redondo","circular"]],
    ["乗る","のる",["to get on","to ride in"],["subirse","entrar (en vehículos)"]],
    ["九","きゅう",["nine"],["nueve","9"],["く"]],
    ["九つ","ここのつ",["nine things"],["9","nueve"]],
    ["九日","ここのか",["nine days","ninth day of the month"],["noveno día del mes"]],
    ["二","に",["two"],["dos","2"]],
    ["二つ","ふたつ",["two things"],["2","dos"]],
    ["二人","ふたり",["two people"],["dos personas","pareja"]],
    ["二十日","はつか",["twenty days","twentieth (day of the month)"],["día 20","veinteavo (día del mes)"]],
    ["二十歳","はたち",["20 years old"],["veinte años","20 años de edad"]],
    ["二日","ふつか",["two days","second day of the month"],["segundo día del mes"]],
    ["五","ご",["five"],["cinco","5"]],
    ["五つ","いつつ",["five things"],["cinco"]],
    ["五日","いつか",["five days","fifth day of the month"],["quinto día del mes"]],
    ["交差点","こうさてん",["intersection"],["cruce"]],
    ["交番","こうばん",["police box"],["puesto de policía"]],
    ["人","ひと",["man","person"],["persona","(sp) las personas"]],
    ["今","いま",["now"],["ahora","momento actual"]],
    ["今年","ことし",["this year"],["este año"]],
    ["今日","きょう",["today","this day"],["hoy","este día"],["こんにち"]],
    ["今晩","こんばん",["tonight","this evening"],["esta noche","hoy en la noche"]],
    ["今月","こんげつ",["this month"],["este mes"]],
    ["今朝","けさ",["this morning"],["esta mañana"]],
    ["今週","こんしゅう",["this week"],["esta semana"]],
    ["仕事","しごと",["work","job"],["trabajo","empleo"]],
    ["休み","やすみ",["holiday","day off"],["descanso"]],
    ["休む","やすむ",["to rest","to have a break"],["descansar","tener un respiro"]],
    ["会う","あう",["to meet","to see"],["conocerse","encontrarse con"]],
    ["会社","かいしゃ",["company","corporation"],["empresa","compañía"]],
    ["伯母さん","おばさん",["aunt"],["(fam) tía","señora de mediana edad"],[],0,1],
    ["伯父","おじ",["uncle"],["tío (menor que el padre de uno)","tío (menor que el padre o la madre de uno)"]],
    ["低い","ひくい",["short","low"],["bajo","humilde"]],
    ["住む","すむ",["to reside","to live in"],["residir","vivir en"]],
    ["体","からだ",["body","health"],["cuerpo","forma"]],
    ["何","なん",["what"],["qué"],["なに"]],
    ["余り","あまり",["not very","surplus"],["resto","restos"],["あんまり"],0,1],
    ["作る","つくる",["to make","to create"],["hacer","crear"]],
    ["作文","さくぶん",["essay","composition"],["composición","escritura"]],
    ["使う","つかう",["to use"],["despachar","enviar"]],
    ["便利","べんり",["convenient","handy"],["conveniente","útil"]],
    ["借りる","かりる",["to borrow","to owe"],["tomar prestado","rentar"]],
    ["傘","かさ",["umbrella","parasol"],["paraguas","parasol"]],
    ["働く","はたらく",["to work"],["trabajar","laborar"]],
    ["元気","げんき",["health(y)","energetic"],["salud","saludable"]],
    ["兄","あに",["(my) older brother (humble)"],["hermano mayor"]],
    ["兄弟","きょうだい",["siblings (humble)","brothers and sisters"],["hermanos","hermanos y hermanas"]],
    ["先","さき",["future","recent"],["antes","adelante"]],
    ["先月","せんげつ",["last month"],["el mes pasado"]],
    ["先生","せんせい",["teacher","professor"],["maestro","profesor"]],
    ["先週","せんしゅう",["last week"],["la última semana","la semana anterior"]],
    ["入る","はいる",["to enter","to contain"],["entrar"],["いる"]],
    ["入れる","いれる",["to put in"],["meter","dejar entrar"]],
    ["入口","いりぐち",["entrance"],["entrada","puerta"]],
    ["全部","ぜんぶ",["all","entire"],["todo","entero"]],
    ["八","はち",["eight"],["ocho","8"]],
    ["八つ","やっつ",["eight things"],["ocho"]],
    ["八日","ようか",["eight days","eighth day of the month"],["octavo día del mes"]],
    ["八百屋","やおや",["greengrocer"],["verdulería","verdulero"]],
    ["公園","こうえん",["a park"],["parque (público)"]],
    ["六","ろく",["six"],["seis","6"]],
    ["六つ","むっつ",["six things"],["6","seis"]],
    ["六日","むいか",["six days","sixth day of month"],["sexto día del mes"]],
    ["写真","しゃしん",["a picture","a photograph"],["fotografía"]],
    ["冬","ふゆ",["winter"],["invierno"]],
    ["冷たい","つめたい",["cold (things, people)"],["fresco","frío"]],
    ["冷蔵庫","れいぞうこ",["refrigerator"],["refrigerador","nevera"]],
    ["出かける","でかける",["to go out","to depart"],["partir","salir (e.g. afuera, de excursión)"]],
    ["出す","だす",["to take (something) out","to hand in (something)"],["salir","sacar"]],
    ["出る","でる",["to appear","to leave"],["aparecer"]],
    ["出口","でぐち",["an exit"],["salida"]],
    ["分かる","わかる",["to understand"],["entender"]],
    ["切る","きる",["to cut","to hang up (a phone)"],["cortar","caer"]],
    ["切手","きって",["postal (postage) stamps"],["sello"]],
    ["切符","きっぷ",["a ticket"],["boleto","billete"]],
    ["初め","はじめ",["beginning","start"],["comienzo","principio"]],
    ["初めて","はじめて",["for the first time"],["primera vez"]],
    ["前","まえ",["before","in front"],["delante","antes"]],
    ["勉強","べんきょう",["study"],["estudio"]],
    ["動物","どうぶつ",["animal"],["animal"]],
    ["勤める","つとめる",["to work (for)"],["servir","estar empleado"]],
    ["北","きた",["north"],["Norte","huir"]],
    ["医者","いしゃ",["doctor","physician"],["doctor","médico"]],
    ["十","じゅう",["ten"],["diez","10"],["とお"]],
    ["十日","とおか",["ten days","tenth day of the month"],["décimo día del mes"]],
    ["千","せん",["thousand"],["mil","muchos"]],
    ["午前","ごぜん",["morning","A.M."],["la mañana","A.M."]],
    ["午後","ごご",["afternoon","P.M."],["la tarde","p.m"]],
    ["半","はん",["half (e.g., にじはん | half-past two)"],["mitad","medio"]],
    ["半分","はんぶん",["half"],["medio","mitad"]],
    ["南","みなみ",["South"],["Sur"]],
    ["危ない","あぶない",["dangerous","critical"],["peligroso","crítico"]],
    ["卵","たまご",["egg"],["huevo","óvulo"]],
    ["厚い","あつい",["kind","warm(hearted)"],["cordial","bueno"]],
    ["去年","きょねん",["last year"],["(el) año pasado"]],
    ["友達","ともだち",["friend"],["amigo","compañero"]],
    ["取る","とる",["to take (a class)","to get (a grade)"],["tomar","coger"]],
    ["口","くち",["job opening","mouth"],["boca","orificio"]],
    ["古い","ふるい",["old (in reference to objects, not people)","aged"],["(objetos) viejo","antiguo"]],
    ["可愛い","かわいい",["cute","adorable"],["bonito","hermoso"],[],0,1],
    ["台所","だいどころ",["kitchen"],["cocina"]],
    ["右","みぎ",["right hand side"],["derecha"]],
    ["同じ","おなじ",["same","identical"],["el mismo","igual"]],
    ["名前","なまえ",["name"],["nombre"]],
    ["向こう","むこう",["beyond","over there"],["más allá","por allí"]],
    ["吸う","すう",["to breathe in","to suck"],["fumar","aspirar"]],
    ["吹く","ふく",["to blow (wind, etc.)"],["soplar"]],
    ["呼ぶ","よぶ",["to call (one's name)","to invite"],["llamar","llamársele"]],
    ["咲く","さく",["to bloom"],["florecer"]],
    ["問題","もんだい",["a problem"],["problema","pregunta"]],
    ["喫茶店","きっさてん",["café"],["cafetería"]],
    ["四","し",["four"],["cuatro","4"],["よん"]],
    ["四つ","よっつ",["four things"],["4","cuatro"]],
    ["四日","よっか",["four days","fourth day of the month"],["cuarto día del mes"]],
    ["困る","こまる",["to be bothered","to have difficulty"],["enfurecerse","preocuparse"]],
    ["図書館","としょかん",["library"],["biblioteca"]],
    ["国","くに",["country","place of origin"],["país"]],
    ["土曜日","どようび",["Saturday"],["sábado"]],
    ["在る","ある",["to be","to have"],["estar (objetos inanimados y plantas)","vivir"],[],0,1],
    ["地下鉄","ちかてつ",["underground train","subway"],["tren subterráneo","metro subterráneo"]],
    ["地図","ちず",["a map"],["mapa"]],
    ["塩","しお",["salt"],["sal"]],
    ["声","こえ",["voice"],["voz","fama"]],
    ["売る","うる",["to sell (v.t.)"],["vender"]],
    ["夏","なつ",["summer"],["verano"]],
    ["夏休み","なつやすみ",["summer vacation"],["vacaciones de verano"]],
    ["夕方","ゆうがた",["late afternoon (typically just before dinner time)","evening"],["tarde","noche"]],
    ["夕飯","ゆうはん",["dinner","supper"],["cena"],["ゆうめし"]],
    ["外","そと",["outside","exterior"],["afuera","exterior"],["がい"]],
    ["外国","がいこく",["foreign country","abroad"],["país extranjero"]],
    ["外国人","がいこくじん",["foreigner"],["extranjero"]],
    ["多い","おおい",["many","there are a lot"],["muchos","numeroso"]],
    ["多分","たぶん",["perhaps","probably"],["tal vez","quizás"]],
    ["夜","よる",["evening","night"],["noche","tarde"]],
    ["大きい","おおきい",["big","large"],["grande","largo"]],
    ["大きな","おおきな",["big"],["grande","gran"]],
    ["大丈夫","だいじょうぶ",["It's ok (all right)","No need to worry"],["estar a salvo","estar bien"]],
    ["大人","おとな",["adult"],["adulto","persona mayor"]],
    ["大使館","たいしかん",["embassy"],["embajada"]],
    ["大切","たいせつ",["important"],["importante","valioso"]],
    ["大勢","おおぜい",["great number of people"],["muchos","numerosos"]],
    ["大変","たいへん",["very","difficult"],["muy"]],
    ["大好き","だいすき",["very like-able","like very much"],["adorable","muy agradable"]],
    ["大学","だいがく",["college","university"],["universidad"]],
    ["天気","てんき",["weather"],["clima","los elementos"]],
    ["太い","ふとい",["fat","thick"],["gordo","obeso"]],
    ["奥さん","おくさん",["(someone else's) wife (hon.)"],["esposa","señora"]],
    ["女","おんな",["woman","female"],["femenino","mujer"]],
    ["女の子","おんなのこ",["girl"],["chica","muchacha"]],
    ["好き","すき",["liking","fondness"],["gustar","gustado"]],
    ["妹","いもうと",["younger sister (humble)"],["hermana menor"]],
    ["姉","あね",["(my) older sister (humble)"],["hermana mayor"]],
    ["始まる","はじまる",["(something) begins"],["comenzar"]],
    ["嫌","いや",["disagreeable","detestable"],["antipatía","aversión"]],
    ["嫌い","きらい",["dislike"],["disgusto","odio"]],
    ["子供","こども",["child(ren)"],["niño","niños"]],
    ["字引","じびき",["dictionary"],["diccionario"]],
    ["学校","がっこう",["a school"],["escuela"]],
    ["学生","がくせい",["student"],["estudiante","alumno"]],
    ["安い","やすい",["inexpensive","cheap (things)"],["barato"]],
    ["家","いえ",["house","home"],["casa"],["うち","け"]],
    ["家庭","かてい",["home","family"],["hogar","familia"]],
    ["家族","かぞく",["family","members of a family"],["familia","miembros de la familia"]],
    ["宿題","しゅくだい",["homework"],["deberes","tareas escolares"]],
    ["寒い","さむい",["cold (in reference to weather)"],["frío (ej. clima)"]],
    ["寝る","ねる",["to sleep","to go to sleep"],["acostarse","dormir"]],
    ["封筒","ふうとう",["envelope"],["sobre (para cartas)"]],
    ["小さい","ちいさい",["small","little"],["pequeño"]],
    ["小さな","ちいさな",["small","little"],["pequeño"]],
    ["少し","すこし",["little","few"],["pequeña cantidad","poco"]],
    ["少ない","すくない",["a little","a few"],["poco","un poco"]],
    ["居る","おる",["to be (animate)","to be"],["estar (objetos animados)","existir"],[],0,1],
    ["山","やま",["mountain"],["montaña"]],
    ["川","かわ",["river"],["arroyo","río"]],
    ["左","ひだり",["left hand side"],["izquierda"]],
    ["差す","さす",["to raise (stretch out) hands","to raise (e.g., umbrella)"],["extender la mano","abrir el paraguas"]],
    ["帰る","かえる",["to go back","to go home"],["regresar","enviar de regreso"]],
    ["帽子","ぼうし",["hat","cap"],["sombrero"]],
    ["平仮名","ひらがな",["hiragana"],["hiragana","48 silabas"]],
    ["年","とし",["year","age"],["año","edad"],["ねん"]],
    ["広い","ひろい",["spacious","wide"],["espacioso","vasto"]],
    ["店","みせ",["store","shop"],["tienda","comercio"],["てん"]],
    ["座る","すわる",["to sit"],["sentarse","ponerse en cuclillas"]],
    ["庭","にわ",["garden"],["patio","jardín"]],
    ["廊下","ろうか",["corridor"],["corredor"]],
    ["建物","たてもの",["building"],["edificio"]],
    ["引く","ひく",["to pull","to draw"],["tensar","estirar"]],
    ["弟","おとうと",["younger brother"],["hermano menor"]],
    ["弱い","よわい",["weak"],["débil","endeble"]],
    ["強い","つよい",["strong","powerful"],["fuerte","poderoso"]],
    ["弾く","ひく",["to play (a string instrument or piano)"],["tocar (un instrumento)"]],
    ["待つ","まつ",["to wait"],["esperar de","tener la esperanza puesta en"]],
    ["後","あと",["afterwards (later)","in the future"],["después","luego"],["のち","ご"]],
    ["後ろ","うしろ",["back","behind"],["detrás","atrás"]],
    ["御飯","ごはん",["rice (cooked)","meal"],["arroz (cocinado)","platillo"]],
    ["忘れる","わすれる",["to forget"],["olvidar"]],
    ["忙しい","いそがしい",["busy (people, days)"],["ocupado","irritado"]],
    ["悪い","わるい",["bad","sinful"],["malo","pobre"]],
    ["意味","いみ",["meaning","significance"],["significado"]],
    ["戸","と",["door (Japanese style)"],["puerta","casa"]],
    ["所","ところ",["place"],["lugar"]],
    ["手","て",["hand"],["mano"]],
    ["手紙","てがみ",["letter"],["carta"]],
    ["押す","おす",["to push","to press"],["empujar","presionar"]],
    ["持つ","もつ",["to hold","to carry"],["llevar","cargar"]],
    ["掃除","そうじ",["cleaning","sweeping"],["limpieza","hacer la limpieza"]],
    ["授業","じゅぎょう",["a class (of school)"],["clase","lección"]],
    ["掛ける","かける",["to put on (e.g., glasses)","to hang (e.g., on a wall)"],["colgar","elevar"]],
    ["撮る","とる",["to take (a photo)","to make (a film)"],["grabar (vídeo, audio, etc.)","tomar (foto)"]],
    ["教える","おしえる",["to teach","to inform"],["enseñar","informar"]],
    ["教室","きょうしつ",["classroom"],["aula","clase"]],
    ["散歩","さんぽ",["walk","stroll"],["paseo"]],
    ["文章","ぶんしょう",["sentence","text"],["frase","escrito"]],
    ["料理","りょうり",["cooking","cuisine"],["cocina","arte culinario"]],
    ["新しい","あたらしい",["new"],["nuevo"]],
    ["新聞","しんぶん",["newspaper"],["periódico","rotativo"]],
    ["方","かた",["-- honorific form for 人 (ひと) --","way of doing"],["dirección"],["ほう"]],
    ["旅行","りょこう",["travel","trip"],["viajar","viaje"]],
    ["日曜日","にちようび",["Sunday"],["domingo"]],
    ["早い","はやい",["early"],["rápido","ágil"]],
    ["明るい","あかるい",["bright (in reference to personality or weather)","cheerful"],["claro","luminoso"]],
    ["明後日","あさって",["day after tomorrow"],["pasado mañana"],["みょうごにち"]],
    ["明日","あした",["tomorrow"],["mañana"],["あす","みょうにち"]],
    ["易しい","やさしい",["easy","plain"],["fácil","simple"]],
    ["映画","えいが",["movie","film"],["cine","película"]],
    ["映画館","えいがかん",["movie theater","cinema"],["(sala de) cine"]],
    ["春","はる",["spring"],["primavera","comienzo del año"]],
    ["昨夜","ゆうべ",["last night"],["anoche"],["さくや"]],
    ["昨日","きのう",["yesterday"],["ayer"],["さくじつ"]],
    ["昼","ひる",["noon","daytime"],["día","mediodía"]],
    ["昼御飯","ひるごはん",["lunch","midday meal"],["almuerzo"]],
    ["時々","ときどき",["sometimes"],["a veces"]],
    ["時計","とけい",["a watch","a clock"],["reloj","reloj de mano"]],
    ["時間","じかん",["time"],["tiempo"]],
    ["晩","ばん",["evening"],["tarde","noche"]],
    ["晩御飯","ばんごはん",["dinner","evening meal"],["cena"]],
    ["晴れ","はれ",["clear (sunny) weather"],["despejado (cielo)","calidad excelente"]],
    ["晴れる","はれる",["to be sunny"],["estar soleado","despejarse"]],
    ["暇","ひま",["free time","leisure"],["tiempo libre","descanso"]],
    ["暑い","あつい",["hot (in reference to weather)","warm"],["caliente","cálido (clima)"]],
    ["暖かい","あたたかい",["warm"],["cálido","afable"]],
    ["暗い","くらい",["dark","gloomy"],["sombrío","oscuro"]],
    ["曇り","くもり",["cloudiness","cloudy weather"],["nublado"]],
    ["曇る","くもる",["to become cloudy","to become dim"],["nublarse"]],
    ["曲る","まがる",["to turn","to bend"],["voltear","girar"]],
    ["書く","かく",["to write"],["escribir"]],
    ["月曜日","げつようび",["Monday"],["lunes"]],
    ["有る","ある",["to be","to have"],["estar (objetos inanimados y plantas)","vivir"],[],0,1],
    ["有名","ゆうめい",["famous"],["famoso"]],
    ["服","ふく",["clothes"],["ropa","admitir"]],
    ["朝","あさ",["morning"],["mañana","amanecer"]],
    ["朝御飯","あさごはん",["breakfast"],["desayuno"]],
    ["木","き",["tree","wood"],["árbol","madera"]],
    ["木曜日","もくようび",["Thursday"],["jueves"]],
    ["本","ほん",["book"],["libro","volumen"]],
    ["本当","ほんとう",["real","true"],["real","verdadero"]],
    ["本棚","ほんだな",["bookshelf"],["estante para libros"]],
    ["机","つくえ",["desk"],["mesa","escritorio"]],
    ["村","むら",["village"],["ciudad","pueblo"]],
    ["来る","くる",["to come"],["llegar","venir"]],
    ["来年","らいねん",["next year"],["(el) próximo año","(el) año que viene"]],
    ["来月","らいげつ",["next month"],["mes entrante","mes siguiente"]],
    ["来週","らいしゅう",["next week"],["semana entrante","semana siguiente"]],
    ["東","ひがし",["east"],["Este"]],
    ["果物","くだもの",["fruit"],["fruta"]],
    ["椅子","いす",["chair"],["silla"]],
    ["楽しい","たのしい",["enjoyable","fun"],["divertido"]],
    ["横","よこ",["beside","side"],["lateral","lado"]],
    ["橋","はし",["bridge"],["puente"]],
    ["次","つぎ",["next"],["siguiente","seguir"]],
    ["欲しい","ほしい",["to want","in need of"],["deseado","deseado por"]],
    ["歌","うた",["a song"],["canción","cantar"]],
    ["歌う","うたう",["to sing"],["cantar"]],
    ["止まる","とまる",["to come to a halt"],["detenerse","permanecer"],["とどまる"]],
    ["歩く","あるく",["to walk"],["caminar"]],
    ["歯","は",["tooth"],["diente","diente de engranaje"]],
    ["死ぬ","しぬ",["to die"],["morir"]],
    ["段々","だんだん",["gradually","by degrees"],["gradualmente"]],
    ["母","はは",["(my) mother"],["madre","base"]],
    ["毎年","まいねん",["every year","yearly"],["cada año","anualmente"],["まいとし"]],
    ["毎日","まいにち",["every day"],["todos los días"]],
    ["毎晩","まいばん",["every night"],["cada noche","todas las noches"]],
    ["毎月","まいげつ",["every month","monthly"],["cada mes","mensualmente"],["まいつき"]],
    ["毎朝","まいあさ",["every morning"],["cada mañana"]],
    ["毎週","まいしゅう",["every week"],["cada semana"]],
    ["水","みず",["water"],["agua"]],
    ["水曜日","すいようび",["Wednesday"],["miércoles"]],
    ["汚い","きたない",["dirty","unclean"],["sucio","manchado"]],
    ["池","いけ",["pond"],["estanque","lago"]],
    ["沢山","たくさん",["many","much"],["muchos","abundantes"],[],0,1],
    ["泳ぐ","およぐ",["to swim"],["nadar"]],
    ["洋服","ようふく",["Western-style clothes"],["ropa estilo occidental"]],
    ["洗う","あらう",["to wash"],["lavar"]],
    ["洗濯","せんたく",["washing","laundry"],["lavar la ropa","hacer la colada"]],
    ["浴びる","あびる",["to bathe","to shower"],["bañarse","gozar en el sol"]],
    ["海","うみ",["sea","beach"],["mar","océano"]],
    ["消える","きえる",["to vanish","to disappear"],["apagarse","desvanecer"]],
    ["消す","けす",["to erase","to delete"],["borrar"]],
    ["涼しい","すずしい",["cool","refreshing (in reference to weather)"],["fresco","refrescante"]],
    ["渡す","わたす",["to hand (something) over (v.t.)","to get across"],["vadear (un río, etc.)","llevar a través de"]],
    ["渡る","わたる",["to cross over","to go across"],["durar","abarcar"]],
    ["温い","ぬるい",["lukewarm"],["tibio","templado"],[],0,1],
    ["漢字","かんじ",["kanji","Chinese character"],["caracteres chinos","kanji"]],
    ["火曜日","かようび",["Tuesday"],["Martes"]],
    ["灰皿","はいざら",["ashtray"],["cenicero"]],
    ["無くす","なくす",["to lose something"],["perder algo"]],
    ["熱い","あつい",["hot (objects)"],["caliente (cosas)"]],
    ["父","ちち",["(my) father"],["padre"]],
    ["片仮名","かたかな",["katakana"],["katakana"]],
    ["牛乳","ぎゅうにゅう",["milk"],["leche (de vaca)"]],
    ["牛肉","ぎゅうにく",["beef"],["carne de res (vaca, ternera)"]],
    ["物","もの",["thing (concrete object)"],["cosa","objeto"]],
    ["犬","いぬ",["dog"],["perro"]],
    ["狭い","せまい",["narrow","not spacious"],["estrecho"]],
    ["猫","ねこ",["cat"],["gato"]],
    ["玄関","げんかん",["entrance (to a house or a building)"],["recibidor","hall de entrada"]],
    ["甘い","あまい",["generous","sweet"],["dulce","dulzón"]],
    ["生まれる","うまれる",["to be born"],["nacer"]],
    ["生徒","せいと",["student","pupil"],["pupilo"]],
    ["男","おとこ",["man","male"],["masculino","hombre"]],
    ["男の子","おとこのこ",["boy"],["chico","chaval"]],
    ["町","まち",["town","city"],["pueblo","ciudad"]],
    ["留学生","りゅうがくせい",["international student"],[" estudiante en el extranjero"]],
    ["番号","ばんごう",["number","series of digits"],["números","serie de dígitos"]],
    ["疲れる","つかれる",["to get (become) tired","to become fatigued"],["cansar","cansarse de"]],
    ["病気","びょうき",["illness","sickness"],["enfermedad"]],
    ["病院","びょういん",["hospital"],["hospital"]],
    ["痛い","いたい",["hurt","painful"],["doloroso","me duele"]],
    ["登る","のぼる",["to climb"],["elevar","ascender"]],
    ["白","しろ",["white"],["blanco"]],
    ["白い","しろい",["white"],["blanco"]],
    ["百","ひゃく",["hundred"],["cien","muchos"]],
    ["皆さん","みなさん",["all of you","everyone"],["todos"]],
    ["目","め",["eye(s)"],["ojo","mirada"]],
    ["眼鏡","めがね",["eye glasses"],["gafas","(am) lentes"]],
    ["着く","つく",["to arrive at","to reach"],["llegar a","alcanzar"]],
    ["着る","きる",["to put on (clothes above your waist)","to wear"],["vestir","ponerse"]],
    ["知る","しる",["to know","to understand"],["saber","entender"]],
    ["短い","みじかい",["short (length)"],["corto","breve"]],
    ["石鹸","せっけん",["soap"],["jabón"]],
    ["砂糖","さとう",["sugar"],["azúcar"]],
    ["磨く","みがく",["to brush (teeth)","to polish"],["pulir","limar"]],
    ["私","わたし",["I","myself"],["yo"],["あたし"]],
    ["秋","あき",["fall (season)"],["otoño"]],
    ["空","そら",["sky"],["cielo","los cielos"],[],1],
    ["空","から",["emptiness","being empty"],["vacío"],[],1],
    ["窓","まど",["window"],["ventana","habitación"]],
    ["立つ","たつ",["to stand up"],["estar de pie","ponerse de pie"]],
    ["答える","こたえる",["to answer","to reply"],["responder","contestar"]],
    ["箱","はこ",["box"],["caja","cofre"]],
    ["箸","はし",["chopsticks"],["palillos (para comer o cocinar)"]],
    ["紅茶","こうちゃ",["black tea"],["té negro"]],
    ["紙","かみ",["paper"],["papel","periódico"]],
    ["細い","ほそい",["thin","slender"],["delgado","fino"]],
    ["終る","おわる",["to finish","to close"],["terminar","acabar"]],
    ["結婚","けっこん",["marriage"],["matrimonio"]],
    ["結構","けっこう",["splendid","enough"],["que está bien así como está","mucho ~"]],
    ["絵","え",["a painting","a picture"],["cuadro","dibujo"]],
    ["綺麗","きれい",["pretty","clean"],["bonito","bello"]],
    ["緑","みどり",["green"],["verde","verdor"]],
    ["締める","しめる",["to tie","to fasten"],["atar","sujetar"]],
    ["練習","れんしゅう",["practice","training"],["ejercitar","practicar"]],
    ["置く","おく",["to put","to lay"],["poner","colocar"]],
    ["美味しい","おいしい",["delicious","tasty"],["delicioso","sabroso"],[],0,1],
    ["習う","ならう",["to learn"],["aprender"]],
    ["耳","みみ",["ear"],["oreja","oído"]],
    ["聞く","きく",["to hear","to listen"],["oír","escuchar"]],
    ["肉","にく",["meat"],["carne"]],
    ["背","せい",["(one's) height","stature"],["estatura","altura"],["せ"]],
    ["背広","せびろ",["men's suit"],["traje de negocios"]],
    ["脱ぐ","ぬぐ",["to take off (clothes)"],["desvestir","quitar (ropa)"]],
    ["自分","じぶん",["myself","oneself"],["mismo","propio"]],
    ["自動車","じどうしゃ",["automobile"],["automóvil"]],
    ["自転車","じてんしゃ",["bicycle"],["bicicleta"]],
    ["色","いろ",["color"],["color","aspecto"]],
    ["色々","いろいろ",["various"],["diversos","varios"]],
    ["花","はな",["flower"],["flor"]],
    ["花瓶","かびん",["(flower) vase"],["florero"]],
    ["若い","わかい",["young"],["joven"]],
    ["英語","えいご",["English (language)"],["Idioma Inglés","lengua inglesa"]],
    ["茶碗","ちゃわん",["rice bowl"],["taza","tazón"]],
    ["茶色","ちゃいろ",["brown"],["café (castaño, marrón) claro"]],
    ["荷物","にもつ",["luggage","baggage"],["equipaje"]],
    ["葉書","はがき",["postcard"],["tarjeta"]],
    ["薄い","うすい",["thin","weak"],["delgado","ligero"]],
    ["薬","くすり",["medicine"],["medicina","droga"]],
    ["行く","いく",["to go"],["ir"],["ゆく"]],
    ["西","にし",["west"],["Oeste","España"]],
    ["要る","いる",["to need"],["necesitar"]],
    ["見せる","みせる",["to show","to display"],["mostrar"]],
    ["見る","みる",["to see","to look"],["ver","mirar"]],
    ["覚える","おぼえる",["to learn","to commit to memory"],["recordar","recolectar"]],
    ["角","かど",["corner (e.g., desk, pavement)"],["esquina"],["かく"],1],
    ["角","つの",["horn","antler"],["cuerno","asta"],[],1],
    ["言う","いう",["to say"],["decir","contar"],["ゆう"]],
    ["言葉","ことば",["language","word(s)"],["palabra","idioma"]],
    ["話","はなし",["talk (chat)","story"],["cuento","charla"]],
    ["話す","はなす",["to speak"],["hablar"]],
    ["誕生日","たんじょうび",["birthday"],["cumpleaños"]],
    ["読む","よむ",["to read"],["leer"]],
    ["誰","だれ",["who"],["quién","alguien"]],
    ["誰か","だれか",["someone"],["alguien"]],
    ["警官","けいかん",["police officer"],["hombre policía"]],
    ["豚肉","ぶたにく",["pork"],["puerco","carne de cerdo"]],
    ["財布","さいふ",["wallet"],["billetera","cartera"]],
    ["買い物","かいもの",["shopping"],["(las) compras (lit. cosas compradas)"]],
    ["買う","かう",["to buy"],["comprar"]],
    ["貸す","かす",["to lend"],["prestar"]],
    ["貼る","はる",["to post","to paste"],["pegarse","ponerse"]],
    ["質問","しつもん",["question","inquiry"],["pregunta"]],
    ["赤","あか",["red"],["rojo","enrojecer"]],
    ["赤い","あかい",["red"],["rojo"]],
    ["走る","はしる",["to run"],["correr"]],
    ["起きる","おきる",["to get up (e.g., from sleeping)","to happen"],["levantarse"]],
    ["足","あし",["foot","leg"],["pierna","pie"]],
    ["車","くるま",["car","vehicle"],["coche","vehículo"]],
    ["軽い","かるい",["light","non-serious"],["ligero","leve"]],
    ["辛い","からい",["hot and spicy","salty"],["picante"],[],1],
    ["辛い","つらい",["painful","bitter"],["doloroso","decepción amorosa"],[],1],
    ["辞書","じしょ",["dictionary"],["diccionario","léxico"]],
    ["辺","へん",["area","vicinity"],["alrededores","límites"]],
    ["近い","ちかい",["near","close by"],["cerca"]],
    ["近く","ちかく",["nearby","in the neighborhood"],["cerca","vecindario"]],
    ["返す","かえす",["to return something"],["devolver (algo)","restituir"]],
    ["速い","はやい",["fast","quick"],["rápido","ágil"]],
    ["遅い","おそい",["slow","(to be) late"],["tarde","lento"]],
    ["遊ぶ","あそぶ",["to play","to spend time pleasantly"],["jugar","hacer una visita (esp. por placer)"]],
    ["道","みち",["road","street"],["camino","razón"]],
    ["違う","ちがう",["to be different","to differ"],["discrepar","diferir"]],
    ["遠い","とおい",["far (away)","distant"],["lejos","distante"]],
    ["部屋","へや",["a room"],["habitación"]],
    ["郵便局","ゆうびんきょく",["post office"],["oficina postal","oficina de correos"]],
    ["醤油","しょうゆ",["soy sauce"],["shoyu (un tipo de salsa de soja Japonesa)"]],
    ["重い","おもい",["heavy","serious"],["pesado"]],
    ["野菜","やさい",["vegetable"],["verdura","hortaliza"]],
    ["金曜日","きんようび",["Friday"],["viernes"]],
    ["鉛筆","えんぴつ",["pencil"],["lápiz"]],
    ["銀行","ぎんこう",["bank"],["banco"]],
    ["鍵","かぎ",["a lock","a key"],["llave","tecla (piano"]],
    ["長い","ながい",["long","lengthy"],["largo","mucho tiempo"]],
    ["門","もん",["gate"],["puerta"]],
    ["閉まる","しまる",["to close","to be closed"],["cerrarse","estar cerrado"]],
    ["閉める","しめる",["to close","to shut"],["cerrar"]],
    ["開く","あく",["to open","to become open"],["abrirse","quedarse abierto"],["ひらく"]],
    ["開ける","あける",["to open (v.t.)"],["abrir","amanecer"]],
    ["降りる","おりる",["to get off"],["bajarse de un vehículo","salir"]],
    ["降る","ふる",["to precipitate","to fall (e.g., rain, snow, etc.)"],["precipitar","caer (e.g. lluvia)"]],
    ["階段","かいだん",["stairs"],["escaleras"]],
    ["隣","となり",["next to","next door to"],["colindante","vecino"]],
    ["雑誌","ざっし",["magazine","journal"],["revista"]],
    ["難しい","むずかしい",["difficult"],["difícil","difícil"]],
    ["雨","あめ",["rain"],["lluvia"]],
    ["雪","ゆき",["snow"],["nieve"]],
    ["零","れい",["zero","nought"],["cero","nada"]],
    ["電気","でんき",["electricity","(electric) light"],["electricidad"]],
    ["電話","でんわ",["a telephone"],["teléfono"]],
    ["電車","でんしゃ",["electric train"],["tren (eléctrico)"]],
    ["青","あお",["blue"],["azul","verde"]],
    ["青い","あおい",["blue"],["azul","verde"]],
    ["静か","しずか",["quiet","calm"],["calmado (tranquilo","sereno)"]],
    ["面白い","おもしろい",["interesting","amusing"],["interesante","entretenido"]],
    ["靴","くつ",["shoes","footwear"],["zapatos"]],
    ["靴下","くつした",["socks"],["calcetines","calcetines"]],
    ["音楽","おんがく",["Music"],["música","movimiento musical"]],
    ["頭","あたま",["head"],["cabeza"],["かしら"]],
    ["頼む","たのむ",["to request","to ask (a favor)"],["solicitar","pedir"]],
    ["顔","かお",["face (body part)"],["cara","faz"]],
    ["風","かぜ",["wind","breeze"],["viento","brisa"]],
    ["風邪","かぜ",["cold","flu"],["resfrío","resfriado común"]],
    ["飛ぶ","とぶ",["to fly","to hop"],["volar","saltar"]],
    ["飛行機","ひこうき",["airplane"],["avión","aeroplano"]],
    ["食べる","たべる",["to eat"],["comer"]],
    ["食べ物","たべもの",["food"],["comida"]],
    ["食堂","しょくどう",["cafeteria","dining hall"],["comedor"]],
    ["飲み物","のみもの",["drink","beverage"],["bebida"]],
    ["飲む","のむ",["to drink"],["tragar","ingerir"]],
    ["飴","あめ",["(hard) candy"],["golosina","dulce de arroz"]],
    ["駅","えき",["station"],["estación"]],
    ["高い","たかい",["tall","high"],["alto","elevado"]],
    ["魚","さかな",["fish"],["pez","pescado"]],
    ["鳥","とり",["chicken (lit., bird)"],["pájaro","ave"]],
    ["鳴く","なく",["to make sound (animal)"],["cantar (pájaros)","maullar"]],
    ["鶏肉","とりにく",["chicken meat"],["carne de pollo","carne de gallina"]],
    ["黄色","きいろ",["yellow"],["amarillo","ámbar"]],
    ["黄色い","きいろい",["yellow"],["amarillo"]],
    ["黒","くろ",["black"],["negro","maldad"]],
    ["黒い","くろい",["black","dark"],["negro"]],
    ["鼻","はな",["nose"],["nariz","hocico"]]
  ],
  kanji: [
    ["一",["one","one radical (no.1)"],["uno","1"],["イチ","イツ"],["ひと-","ひと.つ"]],
    ["七",["seven"],["siete","7"],["シチ"],["なな","なな.つ","なの"]],
    ["万",["ten thousand","10,000"],["diez mil","muchos"],["マン","バン"],["よろず"]],
    ["三",["three"],["tres","3"],["サン","ゾウ"],["み","み.つ","みっ.つ"]],
    ["上",["above","up"],["arriba","encima","parte superior"],["ジョウ","ショウ","シャン"],["うえ","-うえ","うわ-","かみ","あ.げる"]],
    ["下",["below","down","descend"],["debajo","inferior","debajo de"],["カ","ゲ"],["した","しも","もと","さ.げる","さ.がる"]],
    ["中",["in","inside","middle"],["centro","dentro","interior"],["チュウ"],["なか","うち","あた.る"]],
    ["九",["nine"],["nueve","9"],["キュウ","ク"],["ここの","ここの.つ"]],
    ["二",["two","two radical (no. 7)"],["dos","2"],["ニ","ジ"],["ふた","ふた.つ","ふたたび"]],
    ["五",["five"],["cinco","5"],["ゴ"],["いつ","いつ.つ"]],
    ["人",["person"],["persona"],["ジン","ニン"],["ひと","-り","-と"]],
    ["今",["now"],["ahora","momento actual"],["コン","キン"],["いま"]],
    ["休",["rest","day off","retire"],["descanso","descansar","tomarse un descanso"],["キュウ"],["やす.む","やす.まる","やす.める"]],
    ["何",["what"],["qué"],["カ"],["なに","なん","なに-","なん-"]],
    ["先",["before","ahead","previous"],["antes","adelante","previo"],["セン"],["さき","ま.ず"]],
    ["入",["enter","insert"],["entrar","insertar","admitir"],["ニュウ","ジュ"],["い.る","-い.る","-い.り","い.れる","-い.れ"]],
    ["八",["eight","eight radical (no. 12)"],["ocho","8"],["ハチ","ハツ"],["や","や.つ","やっ.つ","よう"]],
    ["六",["six"],["seis","6"],["ロク","リク"],["む","む.つ","むっ.つ","むい"]],
    ["円",["circle","yen","round"],["circular","redondo","yen"],["エン"],["まる.い","まる","まど","まど.か","まろ.やか"]],
    ["出",["exit","leave","go out"],["salir","dejar","sacar"],["シュツ","スイ"],["で.る","-で","だ.す","-だ.す","い.でる"]],
    ["前",["in front","before"],["antes","delante de"],["ゼン"],["まえ","-まえ"]],
    ["北",["north"],["Norte","huir","perder"],["ホク"],["きた"]],
    ["十",["ten"],["diez","10"],["ジュウ","ジッ","ジュッ"],["とお","と","そ"]],
    ["千",["thousand"],["mil","muchos"],["セン"],["ち"]],
    ["午",["noon","sign of the horse","11AM-1PM"],["mediodía"],["ゴ"],["うま"]],
    ["半",["half","middle","odd number"],["mitad","medio","incompleto"],["ハン"],["なか.ば"]],
    ["南",["south"],["Sur"],["ナン","ナ"],["みなみ"]],
    ["友",["friend"],["amigo","compañero"],["ユウ"],["とも"]],
    ["右",["right"],["derecha"],["ウ","ユウ"],["みぎ"]],
    ["名",["name","noted","distinguished"],["nombre","célebre","distinguido"],["メイ","ミョウ"],["な","-な"]],
    ["四",["four"],["cuatro","4"],["シ"],["よ","よ.つ","よっ.つ","よん"]],
    ["国",["country"],["país"],["コク"],["くに"]],
    ["土",["soil","earth","ground"],["suelo","tierra","Turquía"],["ド","ト"],["つち"]],
    ["外",["outside"],["fuera","exterior","otro"],["ガイ","ゲ"],["そと","ほか","はず.す","はず.れる","と-"]],
    ["大",["large","big"],["grande","muy","mucho"],["ダイ","タイ"],["おお-","おお.きい","-おお.いに"]],
    ["天",["heavens","sky","imperial"],["paraíso","cielo","imperial"],["テン"],["あまつ","あめ","あま-"]],
    ["女",["woman","female"],["femenino","mujer"],["ジョ","ニョ","ニョウ"],["おんな","め"]],
    ["子",["child","sign of the rat","11PM-1AM"],["chiquillo","niño"],["シ","ス","ツ"],["こ","-こ","ね"]],
    ["学",["study","learning","science"],["estudio","aprendizaje","ciencia"],["ガク"],["まな.ぶ"]],
    ["小",["little","small"],["poco","pequeño"],["ショウ"],["ちい.さい","こ-","お-","さ-"]],
    ["山",["mountain"],["montaña"],["サン","セン"],["やま"]],
    ["川",["stream","river","river or three-stroke river radical (no. 47)"],["arroyo","río"],["セン"],["かわ"]],
    ["左",["left"],["izquierda"],["サ","シャ"],["ひだり"]],
    ["年",["year","counter for years"],["año","edad"],["ネン"],["とし"]],
    ["後",["behind","back","later"],["después","atrás","detrás"],["ゴ","コウ"],["のち","うし.ろ","うしろ","あと","おく.れる"]],
    ["日",["day","sun","Japan"],["día","solar","Japón"],["ニチ","ジツ"],["ひ","-び","-か"]],
    ["時",["time","hour"],["tiempo","hora","ocasión"],["ジ"],["とき","-どき"]],
    ["書",["write"],["escritura","escrito","escribir"],["ショ"],["か.く","-が.き","-がき"]],
    ["月",["month","moon"],["mes","luna"],["ゲツ","ガツ"],["つき"]],
    ["木",["tree","wood"],["árbol","madera"],["ボク","モク"],["き","こ-"]],
    ["本",["book","present","main"],["libro","origen","base"],["ホン"],["もと"]],
    ["来",["come","due","next"],["venir","llegar","acercarse"],["ライ","タイ"],["く.る","きた.る","きた.す","き.たす","き.たる"]],
    ["東",["east"],["Este"],["トウ"],["ひがし"]],
    ["校",["exam","school","printing"],["escuela","colegio","centro docente"],["コウ","キョウ"],[]],
    ["母",["mother"],["madre","base","cimientos"],["ボ"],["はは","も"]],
    ["毎",["every"],["siempre","cada","en ese momento"],["マイ"],["ごと","-ごと.に"]],
    ["気",["spirit","mind","air"],["espíritu","mente"],["キ","ケ"],["いき","き"]],
    ["水",["water"],["agua"],["スイ"],["みず","みず-"]],
    ["火",["fire"],["fuego","flama","llama"],["カ"],["ひ","-び","ほ-"]],
    ["父",["father"],["padre"],["フ"],["ちち"]],
    ["生",["life","genuine","birth"],["vida","nacimiento","vivir"],["セイ","ショウ"],["い.きる","い.かす","い.ける","う.まれる","うま.れる"]],
    ["男",["male"],["masculino","hombre"],["ダン","ナン"],["おとこ","お"]],
    ["白",["white"],["blanco"],["ハク","ビャク"],["しろ","しら-","しろ.い"]],
    ["百",["hundred"],["cien","muchos"],["ヒャク","ビャク"],["もも"]],
    ["聞",["hear","ask","listen"],["preguntar","escuchar","rumor"],["ブン","モン"],["き.く","き.こえる"]],
    ["行",["going","journey","carry out"],["ir","fila","línea (texto)"],["コウ","ギョウ","アン"],["い.く","ゆ.く","-ゆ.き","-ゆき","-い.き"]],
    ["西",["west","Spain"],["Oeste","España"],["セイ","サイ","ス"],["にし"]],
    ["見",["see","hopes","chances"],["vista","ver","esperanza"],["ケン"],["み.る","み.える","み.せる"]],
    ["話",["tale","talk"],["cuento","charla","hablar"],["ワ"],["はな.す","はなし"]],
    ["語",["word","speech","language"],["palabra","discurso","lenguaje"],["ゴ"],["かた.る","かた.らう"]],
    ["読",["read"],["leer"],["ドク","トク","トウ"],["よ.む","-よ.み"]],
    ["車",["car"],["coche","vehículo","rueda"],["シャ"],["くるま"]],
    ["金",["gold"],["oro","dinero","metal"],["キン","コン","ゴン"],["かね","かな-","-がね"]],
    ["長",["long","leader","superior"],["largo","jefe","sobresaliente"],["チョウ"],["なが.い","おさ"]],
    ["間",["interval","space"],["intervalo","espacio","habitación"],["カン","ケン"],["あいだ","ま","あい"]],
    ["雨",["rain"],["lluvia"],["ウ"],["あめ","あま-","-さめ"]],
    ["電",["electricity"],["electricidad","eléctrico"],["デン"],[]],
    ["食",["eat","food"],["alimento","comida","eclipse"],["ショク","ジキ"],["く.う","く.らう","た.べる","は.む"]],
    ["高",["tall","high","expensive"],["alto","caro","sobresaliente"],["コウ"],["たか.い","たか","-だか","たか.まる","たか.める"]],
    ["飴",["rice jelly","candy"],["golosina","dulce de arroz"],["イ","シ"],["あめ","やしな.う"]],
    ["鍵",["key"],["llave","tecla (piano","órgano"],["ケン"],["かぎ"]],
    ["誰",["who","someone","somebody"],["quién","alguien"],["スイ"],["だれ","たれ","た"]],
    ["箸",["chopsticks"],["palillos (para comer o cocinar)"],["チョ","チャク"],["はし"]],
    ["椅",["chair"],["silla","asiento"],["イ"],[]],
    ["醤",["a kind of miso"],["tipo de miso"],["ショウ"],["ひしお"]],
    ["鹸",["saltiness"],["salinidad","salmuera","jabón"],["ケン","カン","セン"],["あ.く"]],
    ["貼",["stick","paste","apply"],["pegar","engomar","aplicar"],["テン","チョウ"],["は.る","つ.く"]]
  ]
});
